// A local slash command in a single-segment session: live, cc emits ONE echo for
// it (Instance.setEffort, or a command typed through prompt()), while the CLI
// persists it as the isMeta `<local-command-caveat>` line, the `<command-name>`
// line and a `system/local_command` line. A later bubble's fork/rewind target
// must not shift, and the command bubble itself must be forkable. The fake CLI
// writes no jsonl, so each test appends the real sdk-cli shape as the turn ends.

import { test, before, after, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert/strict';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { bootServer, api, waitFor, freshProjectsRoot, rmrf } from './helpers.mjs';
import { encodeCwd, sessionFilePath } from '../src/projects.ts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCENARIO = path.join(__dirname, 'fixtures', 'scenario-resume.json');

let ctx, home;
before(async () => { ctx = await bootServer({ scenarioPath: SCENARIO }); });
after(async () => { await ctx.close(); });
beforeEach(async () => {
  const r = await freshProjectsRoot();
  home = r.home;
  ctx.projectsRoot = r.projectsRoot;
  ctx.claudeProjectsRoot = r.claudeProjectsRoot;
});
afterEach(async () => { await ctx.instances.shutdown(); await rmrf(home); });

const SEED = [
  { type: 'user', uuid: 'u0', message: { role: 'user', content: 'first' } },
  { type: 'assistant', uuid: 'a0', message: { id: 'm0', role: 'assistant', content: [{ type: 'text', text: 'first reply' }] } },
  { type: 'user', uuid: 'u1', message: { role: 'user', content: 'second' } },
  { type: 'assistant', uuid: 'a1', message: { id: 'm1', role: 'assistant', content: [{ type: 'text', text: 'second reply' }] } },
];

// The three lines the sdk-cli persists for a local command `/<name> <args>`.
function localCommandLines(tag, name, args) {
  return [
    { type: 'user', isMeta: true, uuid: `${tag}-caveat`, message: { role: 'user', content:
      '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>' } },
    { type: 'user', uuid: `${tag}-cmd`, message: { role: 'user', content:
      `<command-name>/${name}</command-name>\n            <command-message>${name}</command-message>\n            <command-args>${args}</command-args>` } },
    { type: 'system', subtype: 'local_command', uuid: `${tag}-stdout`, content: `<local-command-stdout>set ${name}</local-command-stdout>` },
  ];
}

const parseLines = (text) => text.split('\n').filter(l => l.length).map(l => JSON.parse(l));

async function resumeSeeded(project) {
  await api(ctx.baseUrl, 'POST', '/api/projects', { name: project });
  const sid = '0c0c0c0c-0000-4000-8000-00000000000' + project.length;
  const dir = path.join(ctx.claudeProjectsRoot, encodeCwd(path.join(ctx.projectsRoot, project)));
  await fs.mkdir(dir, { recursive: true });
  const file = path.join(dir, `${sid}.jsonl`);
  await fs.writeFile(file, SEED.map(l => JSON.stringify(l)).join('\n') + '\n');
  const r = await api(ctx.baseUrl, 'POST', '/api/instances', { project, mode: 'bypassPermissions', resume: sid });
  assert.equal(r.status, 201, JSON.stringify(r.body));
  const inst = ctx.instances.get(r.body.id);
  await waitFor(() => inst.status === 'idle');
  assert.equal(inst._userEchoCount, 2, 'fixture: two prompts resumed');
  return { inst, id: r.body.id, file };
}

const append = (file, lines) => fs.appendFile(file, lines.map(l => JSON.stringify(l)).join('\n') + '\n');

// Run the command (1 live echo), persist its lines, then a later prompt and its
// reply; returns the two bubbles as the ring holds them.
async function commandThenPrompt({ inst, file }, { run, name, args, commandText }) {
  await run();
  await waitFor(() => inst.status === 'idle');
  await append(file, localCommandLines(name, name, args));
  // The scenario scripts one turn, so this prompt's turn stays open; a fork
  // needs no idle instance.
  await inst.prompt('after command');
  await append(file, [
    { type: 'user', uuid: 'u-after', message: { role: 'user', content: [{ type: 'text', text: 'after command' }] } },
    { type: 'assistant', uuid: 'a-after', message: { id: 'm-after', role: 'assistant', content: [{ type: 'text', text: 'ok' }] } },
  ]);
  const echoes = inst.ringSnapshot().filter(e => e.kind === 'user_echo');
  const cmd = echoes.find(e => e.text === commandText);
  const later = echoes.find(e => e.text === 'after command');
  assert.equal(cmd?.userIndex, 2, 'fixture: the command bubble is stamped 2');
  assert.equal(later?.userIndex, 3, 'fixture: the later bubble is stamped 3');
  return { cmd, later };
}

// A jsonl's conversation records: the resume-picker metadata cc appends is not
// part of what a fork is asserted to copy.
const conversation = (text) => parseLines(text).filter(r => r.type !== 'last-prompt' && r.type !== 'permission-mode');

async function assertForks(inst, id, file, { cmd, later }) {
  const src = conversation(await fs.readFile(file, 'utf8'));
  const readFork = async (sid) => conversation(await fs.readFile(sessionFilePath(inst.transcriptPlace, sid), 'utf8'));

  const fkLater = await api(ctx.baseUrl, 'POST', `/api/instances/${id}/fork`, { userMessageIndex: later.userIndex, text: later.text });
  assert.equal(fkLater.status, 201, JSON.stringify(fkLater.body));
  assert.equal(fkLater.body.droppedText, 'after command', 'the later bubble forks at its own prompt');
  const laterPrefix = await readFork(fkLater.body.newSessionId);
  assert.deepEqual(laterPrefix.map(r => r.uuid), src.slice(0, src.findIndex(r => r.uuid === 'u-after')).map(r => r.uuid),
    'the prefix keeps the command lines and ends before the later prompt');

  const fkCmd = await api(ctx.baseUrl, 'POST', `/api/instances/${id}/fork`, { userMessageIndex: cmd.userIndex, text: cmd.text });
  assert.equal(fkCmd.status, 201, JSON.stringify(fkCmd.body));
  assert.equal(fkCmd.body.droppedText, cmd.text, 'the composer is prefilled with the command form');
  const cmdPrefix = await readFork(fkCmd.body.newSessionId);
  assert.deepEqual(cmdPrefix.map(r => r.uuid), ['u0', 'a0', 'u1', 'a1'],
    'forking at the command bubble drops its caveat with it');
}

test('a live /effort does not shift later fork targets', async () => {
  const booted = await resumeSeeded('effort');
  const bubbles = await commandThenPrompt(booted, {
    run: () => booted.inst.setEffort('high'), name: 'effort', args: 'high', commandText: '/effort high',
  });
  await assertForks(booted.inst, booted.id, booted.file, bubbles);
});

test('a typed local slash command does not shift later fork targets', async () => {
  const booted = await resumeSeeded('model');
  const bubbles = await commandThenPrompt(booted, {
    run: () => booted.inst.prompt('/model opus'), name: 'model', args: 'opus', commandText: '/model opus',
  });
  await assertForks(booted.inst, booted.id, booted.file, bubbles);
});
