// Multi-segment fixtures: a session whose backing jsonl rotated (renew/prune)
// while one instance stayed live across the rotation. The fake engine writes no
// jsonl and its `/clear` turn mints one fixed session id, so a live rotation is
// driven here instead: `rotate` feeds the rotation `system/init` through the
// PRODUCTION rotation branch (Instance._handleStdoutLine), and the post-seam
// ring content is either replayed from the seeded file (`replaySlice`, the
// live-shaped content whose correlation keys match the file by construction) or
// emitted as content no seeded file recorded (`emitLive`).

import { promises as fs } from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { api, waitFor } from './helpers.mjs';
import { encodeCwd, transcriptRoot, orchStoreRoot, localPlace } from '../src/projects.ts';
import { loadPersistedTranscript } from '../src/transcript.ts';

// The records the CLI writes at the head of a post-`/clear` jsonl, ahead of the
// first real prompt. The two user lines replay as outer echoes the live ring
// never emits (and the local_command line replays to nothing); how many such
// records precede the first real prompt varies, which is why the pager
// measures the live→file ordinal offset instead of assuming one.
export const RENEW_HEAD = [
  { type: 'user', isMeta: true, uuid: 'head-caveat', message: { role: 'user', content:
    '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>' } },
  { type: 'user', uuid: 'head-clear', message: { role: 'user', content:
    '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>' } },
  { type: 'system', subtype: 'local_command', uuid: 'head-stdout', content: '<local-command-stdout></local-command-stdout>' },
];

// `n` prompt/reply turns, unique per `tag` (uuid, message.id and text).
export function segmentTurns(tag, n) {
  const lines = [];
  for (let i = 0; i < n; i++) {
    lines.push({ type: 'user', uuid: `${tag}-u${i}`, message: { role: 'user', content: `${tag} prompt ${i}` } });
    lines.push({ type: 'assistant', uuid: `${tag}-a${i}`, message: { id: `${tag}-m${i}`, role: 'assistant', content: [
      { type: 'text', text: `${tag} reply ${i}` },
    ] } });
  }
  return lines;
}

// The records actually on disk for a segment: a renew file opens with RENEW_HEAD.
function fileRecords(seg) {
  return seg.reason === 'renew' ? RENEW_HEAD.concat(seg.records) : seg.records;
}

export async function writeSegmentFile(place, seg) {
  const dir = path.join(transcriptRoot(place), encodeCwd(place.cwd));
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, `${seg.id}.jsonl`),
    fileRecords(seg).map(r => JSON.stringify(r)).join('\n') + '\n');
}

// Write every segment's jsonl, and one lineage row for `publicId` holding
// `segments[0..rowThrough]` (its `current` is the last of those).
export async function seedSegmentChain({ place, publicId, segments, rowThrough = segments.length - 1 }) {
  assert.equal(segments[0].reason, 'initial', 'a chain opens on its initial segment');
  for (const seg of segments) await writeSegmentFile(place, seg);
  const row = segments.slice(0, rowThrough + 1);
  const file = path.join(orchStoreRoot(), 'session-lineage.json');
  let sessions = {};
  try { ({ sessions } = JSON.parse(await fs.readFile(file, 'utf8'))); } catch { /* first row */ }
  sessions[publicId] = {
    current: row[row.length - 1].id,
    segments: row.map((s, i) => ({ id: s.id, reason: s.reason, at: `2026-09-0${1 + i}T00:00:00Z` })),
  };
  await fs.mkdir(orchStoreRoot(), { recursive: true });
  await fs.writeFile(file, JSON.stringify({ sessions }, null, 2) + '\n');
}

// A live rotation onto backing id `id`, through the production rotation branch
// — the seam and the `renew` lineage write come from the real writers.
export async function rotate(inst, id) {
  inst._handleStdoutLine(JSON.stringify({ type: 'system', subtype: 'init', session_id: id, model: inst.model }));
  await inst.flushLineage();
}

// Emit, as live ring content, the replayed events of records [from, to) of
// segment file `id` (record indices exclude a renew file's RENEW_HEAD).
export async function replaySlice(inst, place, id, { from = 0, to = Infinity } = {}) {
  const result = await loadPersistedTranscript({ place, sessionId: id, seqHint: 0 });
  assert.ok(result, `segment file ${id} exists`);
  const head = result.lines.length && isRenewFile(result) ? RENEW_HEAD.length : 0;
  for (const line of result.lines.slice(head + from, head + to)) {
    for (const ev of line.events) inst._emitUi(ev);
  }
}

// A renew file's first replayed event is RENEW_HEAD's caveat echo.
function isRenewFile(result) {
  const first = result.lines[0]?.events[0];
  return first?.kind === 'user_echo' && first.text === RENEW_HEAD[0].message.content;
}

// Live content no seeded file recorded: an optional outer echo, then `blocks`
// text blocks of message `msgId` (which must be absent from every seeded file).
export function emitLive(inst, { echo = null, msgId, blocks }) {
  if (echo != null) inst._emitUi({ kind: 'user_echo', text: echo, parentToolUseId: null });
  for (let b = 0; b < blocks; b++) {
    inst._emitUi({ kind: 'text_delta', msgId, blockIdx: b, text: `${msgId} block ${b}`, parentToolUseId: null });
    inst._emitUi({ kind: 'text_end', msgId, blockIdx: b, parentToolUseId: null });
  }
}

// Rotate onto segment `id`, then replay its whole file as live content.
export async function crossSeam(inst, { id, place }) {
  await rotate(inst, id);
  await replaySlice(inst, place, id);
}

export async function withRingCap(ringCap, fn) {
  const prev = process.env.ORCH_EVENT_RING_CAP;
  process.env.ORCH_EVENT_RING_CAP = String(ringCap);
  try { return await fn(); } finally {
    if (prev === undefined) delete process.env.ORCH_EVENT_RING_CAP;
    else process.env.ORCH_EVENT_RING_CAP = prev;
  }
}

// Resume `publicId` live on segment `liveFrom`, then cross every later
// (renew) segment's seam live. Returns { inst, id, place }.
export async function bootLiveAcrossSeams({ ctx, project, publicId, segments, liveFrom = 0, ringCap }) {
  await api(ctx.baseUrl, 'POST', '/api/projects', { name: project });
  await seedSegmentChain({
    place: localPlace(path.join(ctx.projectsRoot, project)), publicId, segments, rowThrough: liveFrom,
  });
  const id = await withRingCap(ringCap, async () => {
    const r = await api(ctx.baseUrl, 'POST', '/api/instances', {
      project, mode: 'bypassPermissions', resume: publicId,
    });
    assert.equal(r.status, 201, `resume ${publicId}: ${JSON.stringify(r.body)}`);
    return r.body.id;
  });
  const inst = ctx.instances.get(id);
  await waitFor(() => inst.status === 'idle');
  assert.equal(inst.backingSessionId, segments[liveFrom].id, 'resumed onto the live-from segment');
  for (const seg of segments.slice(liveFrom + 1)) {
    assert.equal(seg.reason, 'renew', 'only a renew seam can be crossed live (a prune wipes the ring)');
    await crossSeam(inst, { id: seg.id, place: inst.transcriptPlace });
  }
  return { inst, id, place: inst.transcriptPlace };
}
