// Multi-segment fixtures: a session whose backing jsonl rotated (renew/prune)
// while one instance stayed live across the rotation. The fake engine writes no
// jsonl and its `/clear` turn mints one fixed session id, so a live rotation is
// driven here instead: `rotate` feeds the rotation `system/init` through the
// PRODUCTION rotation branch (Instance._handleStdoutLine), and the post-seam
// ring content is either replayed from the seeded file (`replaySlice`, the
// live-shaped content whose correlation keys match the file by construction) or
// emitted as content no seeded file recorded (`emitLive`).

import { promises as fs, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import assert from 'node:assert/strict';
import { api, waitFor } from './helpers.mjs';
import { encodeCwd, transcriptRoot, orchStoreRoot, localPlace } from '../src/projects.ts';
import { loadPersistedTranscript } from '../src/transcript.ts';

// The records the CLI writes at the head of a post-`/clear` jsonl, ahead of the
// first real prompt. The two user lines replay as outer echoes the live ring
// never emits (and the local_command line replays to nothing); how many such
// records precede the first real prompt varies, which is why the pager
// measures the live→file ordinal offset instead of assuming one.
export const RENEW_HEAD = [
  { type: 'user', isMeta: true, uuid: 'head-caveat', message: { role: 'user', content:
    '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>' } },
  { type: 'user', uuid: 'head-clear', message: { role: 'user', content:
    '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>' } },
  { type: 'system', subtype: 'local_command', uuid: 'head-stdout', content: '<local-command-stdout></local-command-stdout>' },
];

// `n` prompt/reply turns, unique per `tag` (uuid, message.id and text).
export function segmentTurns(tag, n) {
  const lines = [];
  for (let i = 0; i < n; i++) {
    lines.push({ type: 'user', uuid: `${tag}-u${i}`, message: { role: 'user', content: `${tag} prompt ${i}` } });
    lines.push({ type: 'assistant', uuid: `${tag}-a${i}`, message: { id: `${tag}-m${i}`, role: 'assistant', content: [
      { type: 'text', text: `${tag} reply ${i}` },
    ] } });
  }
  return lines;
}

// The records actually on disk for a segment: a renew file opens with RENEW_HEAD.
function fileRecords(seg) {
  return seg.reason === 'renew' ? RENEW_HEAD.concat(seg.records) : seg.records;
}

export async function writeSegmentFile(place, seg) {
  const dir = path.join(transcriptRoot(place), encodeCwd(place.cwd));
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, `${seg.id}.jsonl`),
    fileRecords(seg).map(r => JSON.stringify(r)).join('\n') + '\n');
}

// The `at` stamp a fixture row gives its i-th entry.
const atFor = (i) => `2026-09-${String(1 + i).padStart(2, '0')}T00:00:00Z`;

// Write every segment's jsonl (except one marked `file: false` — a missing
// transcript), and one lineage row for `publicId` holding
// `segments[0..rowThrough]`. A segment marked `dropped: true` is written as a
// tombstone; `current` is the newest entry without one.
export async function seedSegmentChain({ place, publicId, segments, rowThrough = segments.length - 1 }) {
  assert.equal(segments[0].reason, 'initial', 'a chain opens on its initial segment');
  for (const seg of segments) if (seg.file !== false) await writeSegmentFile(place, seg);
  await writeLineageRow(publicId, segments.slice(0, rowThrough + 1));
}

// Write ONE `session-lineage.json` row, preserving every other row in the
// store. No shape check on the chain: this is how a test writes a row the
// production writers could not (a legacy row whose oldest entry is not
// `initial`). `current` is derived — the newest entry without `dropped: true`
// — and one must exist, as the store's row invariant requires.
export async function writeLineageRow(publicId, segments) {
  const file = path.join(orchStoreRoot(), 'session-lineage.json');
  let sessions = {};
  try { ({ sessions } = JSON.parse(await fs.readFile(file, 'utf8'))); } catch (e) {
    if (e.code !== 'ENOENT') throw e;
  }
  const live = segments.filter(s => s.dropped !== true);
  assert.ok(live.length > 0, `writeLineageRow: row ${publicId} has no live entry`);
  sessions[publicId] = {
    current: live[live.length - 1].id,
    segments: segments.map((s, i) => ({
      id: s.id, reason: s.reason, at: s.at ?? atFor(i), ...(s.dropped === true ? { dropped: true } : {}),
    })),
  };
  await fs.mkdir(orchStoreRoot(), { recursive: true });
  await fs.writeFile(file, JSON.stringify({ sessions }, null, 2) + '\n');
}

// A prune-style copy of `records`: every tool_result's content replaced by
// `stub`, every uuid kept (src/sessionPrune.ts keeps the tree intact).
export function stubbedCopy(records, stub) {
  return records.map((r) => {
    const content = r.type === 'user' ? r.message?.content : null;
    if (!Array.isArray(content)) return r;
    return { ...r, message: { ...r.message, content: content.map(b =>
      b?.type === 'tool_result' ? { ...b, content: stub } : b) } };
  });
}

// A live rotation onto backing id `id`, through the production rotation branch
// — the seam and the `renew` lineage write come from the real writers.
export async function rotate(inst, id) {
  inst._handleStdoutLine(JSON.stringify({ type: 'system', subtype: 'init', session_id: id, model: inst.model }));
  await inst.flushLineage();
}

// Emit, as live ring content, the replayed events of records [from, to) of
// segment file `id`. `headSkip` (on by default) is the production live shape at
// a renew seam: the live ring never emits RENEW_HEAD's replay-only echoes, so
// they are skipped and record indices start after them — the file MUST open
// with RENEW_HEAD. Pass `headSkip: false` for a file without one.
export async function replaySlice(inst, place, id, { from = 0, to = Infinity, headSkip = true } = {}) {
  const result = await loadPersistedTranscript({ place, sessionId: id, seqHint: 0 });
  assert.ok(result, `segment file ${id} exists`);
  if (headSkip) {
    const firstEcho = result.lines[0]?.events[0];
    assert.equal(firstEcho?.text, RENEW_HEAD[0].message.content, `headSkip: ${id} does not open with RENEW_HEAD`);
  }
  const head = headSkip ? RENEW_HEAD.length : 0;
  for (const line of result.lines.slice(head + from, head + to)) {
    for (const ev of line.events) inst._emitUi(ev);
  }
}

// Live content no seeded file recorded: an optional outer echo, then `blocks`
// text blocks of message `msgId` (which must be absent from every seeded file).
export function emitLive(inst, { echo = null, msgId, blocks }) {
  if (echo != null) inst._emitUi({ kind: 'user_echo', text: echo, parentToolUseId: null });
  for (let b = 0; b < blocks; b++) {
    inst._emitUi({ kind: 'text_delta', msgId, blockIdx: b, text: `${msgId} block ${b}`, parentToolUseId: null });
    inst._emitUi({ kind: 'text_end', msgId, blockIdx: b, parentToolUseId: null });
  }
}

// Rotate onto segment `id`, then replay its whole file as live content.
// Returns every event emitted while crossing, in emit order.
export async function crossSeam(inst, { id, place }) {
  const emitted = [];
  const onEvent = (ev) => emitted.push(ev);
  inst.on('event', onEvent);
  try {
    await rotate(inst, id);
    await replaySlice(inst, place, id);
  } finally {
    inst.off('event', onEvent);
  }
  return emitted;
}

export async function withRingCap(ringCap, fn) {
  const prev = process.env.ORCH_EVENT_RING_CAP;
  process.env.ORCH_EVENT_RING_CAP = String(ringCap);
  try { return await fn(); } finally {
    if (prev === undefined) delete process.env.ORCH_EVENT_RING_CAP;
    else process.env.ORCH_EVENT_RING_CAP = prev;
  }
}

// Resume `publicId` live on segment `liveFrom`, then cross every later
// (renew) segment's seam live. Returns { inst, id, place, crossed }, where
// `crossed[i]` is every event emitted crossing the i-th later segment's seam.
// `beforeResume` (optional) runs once the chain is seeded and before any
// instance exists — the window in which a read of a segment id reaches that
// segment's own file.
export async function bootLiveAcrossSeams({ ctx, project, publicId, segments, liveFrom = 0, ringCap, beforeResume = null }) {
  await api(ctx.baseUrl, 'POST', '/api/projects', { name: project });
  await seedSegmentChain({
    place: localPlace(path.join(ctx.projectsRoot, project)), publicId, segments, rowThrough: liveFrom,
  });
  if (beforeResume) await beforeResume();
  const id = await withRingCap(ringCap, async () => {
    const r = await api(ctx.baseUrl, 'POST', '/api/instances', {
      project, mode: 'bypassPermissions', resume: publicId,
    });
    assert.equal(r.status, 201, `resume ${publicId}: ${JSON.stringify(r.body)}`);
    return r.body.id;
  });
  const inst = ctx.instances.get(id);
  await waitFor(() => inst.status === 'idle');
  assert.equal(inst.backingSessionId, segments[liveFrom].id, 'resumed onto the live-from segment');
  const crossed = [];
  for (const seg of segments.slice(liveFrom + 1)) {
    assert.equal(seg.reason, 'renew', 'only a renew seam can be crossed live (a prune wipes the ring)');
    crossed.push(await crossSeam(inst, { id: seg.id, place: inst.transcriptPlace }));
  }
  return { inst, id, place: inst.transcriptPlace, crossed };
}

// One MCP tool call over JSON-RPC, unwrapped to the tool's JSON result.
let nextRpcId = 1;
export async function mcpTool(ctx, name, args) {
  const res = await fetch(ctx.baseUrl + '/mcp', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ jsonrpc: '2.0', id: nextRpcId++, method: 'tools/call', params: { name, arguments: args } }),
  });
  const body = await res.json();
  assert.ok(body?.result, `${name} returned no result; body=${JSON.stringify(body)}`);
  return JSON.parse(body.result.content[0].text);
}

// Page GET /api/instances/:id/lineage-events backward until `hasMore` is false,
// enforcing the client's progress rule (public/lazyHistory.js): a page is
// accepted iff its segment is unchanged and its cursor strictly lower, or its
// segment is one this walk has not visited. Returns `events` oldest-first, the
// `cursors` each request used and the raw `pages` newest-first.
export async function walkLineage(ctx, id, { limit = 7, before = null, segment = null } = {}) {
  let events = [];
  const cursors = [];
  const pages = [];
  const visited = new Set([segment]);
  for (let i = 0; i < 400; i++) {
    const q = [`limit=${limit}`];
    if (before != null) q.push(`before=${before}`);
    if (segment != null) q.push(`segment=${encodeURIComponent(segment)}`);
    cursors.push({ segment, before });
    const r = await api(ctx.baseUrl, 'GET', `/api/instances/${id}/lineage-events?${q.join('&')}`);
    assert.equal(r.status, 200, `lineage-events ${q.join('&')}: ${JSON.stringify(r.body)}`);
    pages.push(r.body);
    events = r.body.events.concat(events);
    if (!r.body.hasMore) return { events, cursors, pages };
    const next = r.body.segment ?? null;
    if (next === segment) {
      assert.equal(typeof r.body.nextBefore, 'number', 'a same-segment continuation carries a numeric cursor');
      if (before != null) assert.ok(r.body.nextBefore < before, `the cursor strictly decreases (${r.body.nextBefore} < ${before})`);
    } else {
      assert.ok(!visited.has(next), `segment ${next} is not revisited`);
      visited.add(next);
    }
    segment = next;
    before = r.body.nextBefore ?? null;
  }
  throw new Error('walkLineage: cursor never terminated');
}

// Split a walk at its `segment_seam` dividers, oldest first. The run before
// the first divider has label null; each divider starts a run labelled with
// its `segmentId`. Dividers themselves are in no run.
export function splitAtSeams(events) {
  const runs = [{ label: null, events: [] }];
  for (const e of events) {
    if (e.kind === 'segment_seam') runs.push({ label: e.segmentId, events: [] });
    else runs[runs.length - 1].events.push(e);
  }
  return runs;
}

export const isGap = (e) => e.kind === 'history_gap';

// The client's gap adjacency rule (public/conversation.js _renderHistoryGap,
// public/lazyHistory.js spliceBatchAbove): two adjacent gap markers render as one.
export function collapseGaps(evs) {
  return evs.filter((e, i) => !(isGap(e) && i > 0 && isGap(evs[i - 1])));
}

// Load export `name` of repo-relative module `relPath`, asserting (not
// throwing) when the module or the export does not exist — so a test that
// needs a new export fails on an AssertionError rather than an import error.
const REPO = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export async function newExport(relPath, name) {
  const abs = path.join(REPO, relPath);
  assert.ok(existsSync(abs), `${relPath} exists`);
  const mod = await import(pathToFileURL(abs).href);
  assert.equal(typeof mod[name], 'function', `${relPath} exports ${name}`);
  return mod[name];
}
