/*
 * union.c — the FUSE-union daemon cc mounts under a remote-backed worker.
 *
 * ONE POLICY, NOT A MEASUREMENT INSTRUMENT. This file is a fork of the frozen
 * S3 spike instrument `rig/fuse-union-s3.c`, which had three selectable routing
 * modes and eight knobs because its job was to compare them. Every knob is
 * gone; what is left is the single policy the epic specifies. PROVENANCE.md
 * carries the fork point and one row per intentional divergence.
 *
 * ── what it serves, and to whom ─────────────────────────────────────────────
 *
 * A longest-prefix tier table, loaded from $CC_UNION_PINS and generated by
 * src/systems/fuse/tierTable.ts. Five classes reach this file; a sixth is
 * derived (policy.h):
 *
 *   host     the orchestrator's own filesystem, always, for marked and unmarked
 *            callers alike. The CLI's execution closure lives here: its binary,
 *            ld-linux and its shared objects, $HOME, the session scratch dir,
 *            the specific /etc files the runtime needs.
 *   project  the remote tier, and ONLY for a caller marked as the CLI. There is
 *            no host side to fall back to, by design.
 *   bind     a directory bootstrap.sh mounts the ORCHESTRATOR's own over, after
 *            the union is up. Served here as a read-only synthetic node purely
 *            so the bind target exists — /proc, /sys, /dev must never be tiers
 *            (S1 §7.1: a passthrough serving /proc/self/exe answers with the
 *            DAEMON's identity and breaks a bun single-file executable).
 *   hide     ENOENT, and suppressed from the parent's readdir. The union's own
 *            scaffolding, which it must not serve through itself.
 *   fail     ENOENT on both sides FOR THE MARKED CLI, because the system's
 *            advertisement excluded it or no pin covers it. Also refused at
 *            cc's file-tool seam, so it fails both surfaces. THE ONE
 *            CALLER-SENSITIVE CLASS: for an UNMARKED caller it is substituted
 *            to `host` (policy_caller_tier, policy.h) and a
 *            `served/unmarked-host-served` row names the path.
 *   synth    DERIVED, never written in the pins file: the ancestors of every
 *            pin, so a pinned leaf is reachable without its parents being
 *            served from anywhere. Read-only, fixed attributes.
 *
 * AN UNMATCHED PATH IS `fail`, because T_FAIL is enum index 0 and tier_of
 * returns index 0 for a path no pin matches. The instrument's index 0 was
 * remote-first with a host fallback; that fallback is the "one path, two
 * answers" this architecture exists to remove, and deleting it is why the
 * event log below is the instrument the pin list is derived from.
 *
 * THE `fail` → `host` SUBSTITUTION FOR AN UNMARKED CALLER IS NOT THAT FALLBACK
 * COMING BACK, and the difference is mechanical rather than a matter of degree:
 * it is host-ONLY, keyed on the CALLER and never on the outcome, deterministic,
 * and it fires at exactly one tier. Nothing is tried and then retried
 * elsewhere; at `fail` the marked side has no answer at all, so there is no
 * second answer for one path to have. Which side served an op is always
 * knowable — from the trace's `tier=`/`mark=` columns, and by name from the
 * event log.
 *
 * ── the caller mark ─────────────────────────────────────────────────────────
 *
 * A thread group is marked the first time it resolves $CC_UNION_MARK_PATH — the
 * CLI's own binary. The mark is sticky, survives exec, is keyed on the TGID and
 * is revalidated against /proc field 22 on every check so a recycled pid cannot
 * inherit it. An UNMARKED caller at a project path gets -ENOENT: never the
 * remote's copy, never the host's — with the cwd chain (policy_cwd_exempt) as
 * the sole exemption, `getattr` only. Host-pinned and bind-mounted paths are
 * served to marked and unmarked callers alike, and an unmarked caller at `fail`
 * is served the host. policy.h states the ordering.
 *
 * ── the control channel ─────────────────────────────────────────────────────
 *
 * A unix stream socket at $CC_UNION_CONTROL, one connection per FUSE worker
 * thread, control frames only and never file content (policy.h's codec). No
 * remote-tier op touches the mirror before cc has answered: a bare local stat
 * would report ENOENT for a file that exists remotely and is simply not
 * materialised yet. A wedged cc becomes -EIO on a bounded receive timeout, not
 * an unkillable D state — and never a host fallback, which would look exactly
 * like a containment success.
 *
 * ── zero kernel caching ─────────────────────────────────────────────────────
 *
 * cfg->kernel_cache = 0 here, and attr_timeout/entry_timeout/negative_timeout
 * are all 0 in the mount options cc passes (src/systems/fuse/plan.ts). FUSE's
 * attribute cache is per-inode and this filesystem answers per-caller, so one
 * path measurably answered 15 bytes to `stat` and 33 to `cat` across the
 * routing boundary. policy.h's resolution cache is the caller-aware
 * replacement.
 *
 * ── carried from S1, unchanged ──────────────────────────────────────────────
 *
 * Per-request setfsuid/setfsgid is mandatory, not a tuning knob: S1 §7.2
 * measured that without it the CLI's own Bash tool fails EACCES, because its
 * scratch directory gets created root-owned. Known limit, carried:
 * supplementary groups are NOT switched (setgroups(2) is per-process, not
 * per-thread), so a caller whose access depends on one can be wrongly denied by
 * the daemon-side check. default_permissions means the kernel has already
 * checked the caller's full credentials first, so this is a second gate rather
 * than the only one. It is not equivalent.
 *
 * The self-recursion guard is a LIVENESS precondition, not a routing policy: a
 * caller in the daemon's own thread group must never be served through the
 * remote path, or the daemon blocks on a request only it can answer. Keyed on
 * one tgid, because ancestry — the only key that could describe "the CLI and
 * its children" — is unknowable exactly when it matters (S1 §6 Q2).
 *
 * The trace and the event log record PATHS ONLY, never content, so a
 * credential path may appear in them and a credential never does.
 *
 * ── known limit, recorded rather than defended against ──────────────────────
 *
 * A readdir of a `project` directory lists the mirror's children only, so a
 * host pin NESTED inside a project prefix is reachable by name but absent from
 * its parent's listing. It cannot arise at the default mirror root (the
 * project's own remote path); it can at an advertised root of "/". The event
 * log is the instrument that would surface it.
 *
 * ── environment ─────────────────────────────────────────────────────────────
 *
 *   CC_UNION_HOST_ROOT   host tier root                       (default "/")
 *   CC_UNION_REMOTE      the per-session mirror directory     (required)
 *   CC_UNION_PINS        the tier table file                  (required)
 *   CC_UNION_CONTROL     cc's control socket                  (required)
 *   CC_UNION_MARK_PATH   the path whose resolution marks a thread group
 *                                                             (required)
 *   CC_UNION_CWD         the CLI's cwd INSIDE the chroot, normalised — the
 *                        chain an unmarked caller may traverse (required)
 *   CC_UNION_MNT         the mountpoint, hidden implicitly (recursion guard)
 *   CC_UNION_TRACE       every path the kernel asks about, with caller identity
 *   CC_UNION_EVENTS      the policy event log — a `#` header line, then
 *                        <kind>\t<op>\t<path>\t<reason>\t<pid>\t<tgid>\t
 *                        <comm>\t<cmdline>. The instrument the pin list is
 *                        derived from, and the channel whose `deny` rows must
 *                        be empty by the end. Path, comm and cmdline are
 *                        `policy_escape`d; identity is sampled at POLICY TIME.
 */
#define FUSE_USE_VERSION 31
#define _GNU_SOURCE

#include <fuse.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <dirent.h>
#include <pthread.h>
#include <limits.h>
#include <stdint.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/un.h>
#include <sys/xattr.h>
#include <sys/time.h>
#include <sys/fsuid.h>

#include "policy.h"

static int   host_fd = -1, remote_fd = -1;
static char  host_root[PATH_MAX]   = "/";
static char  remote_root[PATH_MAX] = "";
static pid_t self_tgid = 0;
static const char *mark_path = NULL;

/* ── caller identity, for the trace ─────────────────────────────────────── */
/*
 * pid -> (tgid, ppid, starttime, exe, cmdline), cached; a thread's tgid is
 * fixed for its life. comm is NOT cached and never will be: S1 §8.2 defect 2
 * cached it and every request from the CLI came back labelled comm=bash,
 * because the pid was first seen as the shell that later exec'd into the CLI.
 *
 * TGID AND STARTTIME COME FROM policy.h's READER, not from a second parse here:
 * the policy routes on them and the trace attributes on them, and two readers
 * of /proc for one fact is how they come to disagree.
 */
#define PCACHE_SLOTS 8192
struct pent {
	pid_t         pid, tgid, ppid;
	unsigned long long start;   /* /proc/<pid>/stat field 22 */
	char          exe[192];     /* resolved once, per pid */
	char          cmd[192];     /* full cmdline, NULs -> spaces */
};
static struct pent     pcache[PCACHE_SLOTS];
static pthread_mutex_t pcache_mu = PTHREAD_MUTEX_INITIALIZER;

static void read_exe(pid_t pid, char *out, size_t n)
{
	char buf[64];
	ssize_t r;

	snprintf(buf, sizeof(buf), "/proc/%d/exe", (int)pid);
	if ((r = readlink(buf, out, n - 1)) > 0) {
		out[r] = '\0';
		return;
	}
	/*
	 * /proc/<tgid>/exe is rendered by d_path against the READER's root. The
	 * daemon lives outside the chroot the callers live in, so the link can
	 * come back unreachable; the trace records "<unreadable>" rather than
	 * silently substituting the cmdline, because a column that means two
	 * different things in one file is worse than a gap.
	 */
	snprintf(out, n, "<unreadable>");
}

/*
 * THE TRACE'S CMDLINE, AND THE RENDERING IS THIS FILE'S ALONE.
 *
 * THE READ ITSELF IS policy.h's (`policy_proc.cmdline`), shared with the event
 * log, because two readers of /proc for one fact is how they come to disagree.
 * What is NOT shared is what happens to the bytes: NULs become spaces here --
 * and so does EVERY other control character. A `bash -c` cmdline carries the
 * whole script, newlines included, and an embedded newline splits one trace row
 * into many: the first version of this instrument produced 1662 unparsable rows
 * out of ~3000 for exactly that reason, and the analysis silently dropped them.
 *
 * IT IS LOSSY AND THAT IS DELIBERATE HERE. The trace is line-counted
 * (tests/fuse-trace-count.mjs parses this format) and no consumer recovers argv
 * out of it; the EVENT LOG is where argv fidelity is owed, and `policy_escape`
 * gives it losslessly there. exe is the INTERPRETER for anything script-shaped
 * -- a PreToolUse hook and the Bash forwarder are both /bin/bash -- so the
 * script's own path is in the cmdline and nowhere else, which is why the trace
 * carries one at all.
 */
static void trace_cmdline(pid_t pid, char *out, size_t n)
{
	ssize_t k = policy_proc.cmdline(pid, out, n);
	ssize_t i;

	if (k <= 0) {
		snprintf(out, n, "<gone>");
		return;
	}
	for (i = 0; i < k; i++)
		if ((unsigned char)out[i] < 0x20 || (unsigned char)out[i] == 0x7f)
			out[i] = ' ';
	while (k > 0 && out[k - 1] == ' ')
		out[--k] = '\0';
}

/*
 * Resolve TID -> (TGID, PPID, starttime, exe, cmdline). The entry is
 * REVALIDATED on every hit, unconditionally: the instrument made that a flag so
 * the cost could be measured, and the unvalidated arm was the unsound half. A
 * recycled pid otherwise returns its predecessor's tgid for the life of the
 * daemon, and exec(2) replaces the cmdline and the exe link while leaving pid,
 * tgid and start time untouched — so both the start-time compare and the
 * re-read below are load-bearing, and neither can substitute for the other.
 */
static void resolve_ids(pid_t pid, pid_t *tgid_out, pid_t *ppid_out,
			unsigned long long *start_out, const char **exe_out,
			const char **cmd_out)
{
	size_t slot = ((size_t)pid * 2654435761u) % PCACHE_SLOTS;
	pid_t tgid = -1, ppid = -1;
	unsigned long long start = 0;
	const char *exe = "<gone>", *cmd = "<gone>";
	size_t i;

	pthread_mutex_lock(&pcache_mu);
	for (i = 0; i < 64; i++) {
		struct pent *e = &pcache[(slot + i) % PCACHE_SLOTS];
		if (e->pid == pid) {
			unsigned long long now = policy_proc.starttime(pid);
			if (now != e->start) {
				e->pid = 0;   /* recycled: refill below */
				i--;
				continue;
			}
			read_exe(e->tgid > 0 ? e->tgid : pid, e->exe, sizeof(e->exe));
			trace_cmdline(e->tgid > 0 ? e->tgid : pid, e->cmd, sizeof(e->cmd));
			tgid = e->tgid; ppid = e->ppid;
			start = e->start; exe = e->exe; cmd = e->cmd;
			break;
		}
		if (e->pid == 0) {
			char buf[64];
			FILE *f;

			e->pid = pid; e->tgid = policy_proc.tgid(pid); e->ppid = -1;
			e->start = 0; e->exe[0] = '\0';
			snprintf(buf, sizeof(buf), "/proc/%d/status", (int)pid);
			if ((f = fopen(buf, "r")) != NULL) {
				char line[256];
				while (fgets(line, sizeof(line), f))
					if (strncmp(line, "PPid:", 5) == 0) {
						e->ppid = (pid_t)atoi(line + 5);
						break;
					}
				fclose(f);
			}
			e->start = policy_proc.starttime(pid);
			read_exe(e->tgid > 0 ? e->tgid : pid, e->exe, sizeof(e->exe));
			trace_cmdline(e->tgid > 0 ? e->tgid : pid, e->cmd, sizeof(e->cmd));
			tgid = e->tgid; ppid = e->ppid;
			start = e->start; exe = e->exe; cmd = e->cmd;
			break;
		}
	}
	pthread_mutex_unlock(&pcache_mu);
	*tgid_out  = tgid;
	*ppid_out  = ppid;
	if (start_out) *start_out = start;
	if (exe_out)   *exe_out   = exe;
	if (cmd_out)   *cmd_out   = cmd;
}

/* The trace's comm, over the same shared reader; `<gone>` where the event log
 * would write a `\!` sentinel, because this format has no sentinel namespace
 * and nothing parses it. */
static void trace_comm(pid_t pid, char *out, size_t n)
{
	if (policy_proc.comm(pid, out, n) < 0)
		snprintf(out, n, "<gone>");
}

/*
 * THE self-recursion guard. Not a routing policy -- a liveness precondition.
 * It is the minimum possible key (one tgid) and needs no ancestry walk. Where
 * it fires the path is served from the HOST, which is the one answer that
 * cannot re-enter this daemon.
 */
static int caller_is_self(void)
{
	const struct fuse_context *c = fuse_get_context();

	if ((pid_t)c->pid == self_tgid)
		return 1;
	return policy_proc.tgid((pid_t)c->pid) == self_tgid;
}

/* THE MARKING EVENT, on every routed path. S1 §9.1 measured that this is NOT
 * the marked process's first op: it is the shell that later execs into the CLI,
 * and it does real work first. That window is a property of the launcher. */
static void mark_maybe(const char *path)
{
	if (!mark_path || strcmp(path, mark_path) != 0)
		return;
	policy_mark_tid((pid_t)fuse_get_context()->pid);
}

/* ── trace ──────────────────────────────────────────────────────────────── */

static FILE           *trace_fp = NULL;
static pthread_mutex_t trace_mu = PTHREAD_MUTEX_INITIALIZER;

/*
 * `cflags` IS THE FRAME INTENT THE OP DECLARED — the same CCU_FLAG_* byte the
 * FETCH carried — and it is in the line because a trace that cannot separate a
 * READ open from a WRITE open cannot answer the two-handle question the epic
 * carries as a standing condition (PROVENANCE D13c, measurement M6). `0` where
 * the op sent no frame of its own, which is every `fh` branch below.
 */
static void tr(const char *op, const char *path, const char *tier, unsigned cflags)
{
	const struct fuse_context *ctx;
	char comm[24];
	const char *exe, *cmd;
	pid_t tgid, ppid;
	unsigned long long start;

	if (!trace_fp)
		return;
	ctx = fuse_get_context();
	resolve_ids((pid_t)ctx->pid, &tgid, &ppid, &start, &exe, &cmd);
	trace_comm((pid_t)ctx->pid, comm, sizeof(comm));

	pthread_mutex_lock(&trace_mu);
	fprintf(trace_fp,
		"%s\t%s\ttier=%s cflags=%u pid=%d uid=%d gid=%d tgid=%d ppid=%d "
		"comm=%s mark=%d exe=%s cmd=%s\n",
		op, path, tier, cflags, (int)ctx->pid, (int)ctx->uid,
		(int)ctx->gid, (int)tgid, (int)ppid, comm, mark_of(tgid), exe, cmd);
	pthread_mutex_unlock(&trace_mu);
}

/* ── the control channel's transport ────────────────────────────────────── */
/*
 * ONE CONNECTION PER FUSE WORKER THREAD, opened lazily and held in a
 * pthread_key with a destructor, so a request never waits on another thread's
 * reply and a retired thread does not leak its fd. Blocking per request, as the
 * epic licenses.
 *
 * SO_RCVTIMEO IS THE WHOLE LIVENESS ARGUMENT: without it a cc that stops
 * answering leaves the calling thread in an uninterruptible FUSE wait, and the
 * mount can only be recovered by aborting the connection. With it the op fails
 * -EIO, the daemon logs a refusal, and teardown proceeds normally.
 */
#define CONTROL_TIMEOUT_MS 120000

static const char *control_path = NULL;
static pthread_key_t control_key;

/* Stored as fd+1, so a live fd 0 is distinguishable from "no connection" and
 * the key's destructor actually runs (pthread_setspecific(NULL) suppresses it). */
static void control_close(void *v)
{
	int fd = (int)(intptr_t)v - 1;
	if (fd >= 0)
		close(fd);
}

static int control_connect(void)
{
	struct sockaddr_un sa;
	struct timeval tv;
	int fd;

	if (!control_path || strlen(control_path) >= sizeof(sa.sun_path))
		return -1;
	if ((fd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0)) == -1)
		return -1;
	memset(&sa, 0, sizeof(sa));
	sa.sun_family = AF_UNIX;
	snprintf(sa.sun_path, sizeof(sa.sun_path), "%s", control_path);
	if (connect(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
		close(fd);
		return -1;
	}
	tv.tv_sec  = CONTROL_TIMEOUT_MS / 1000;
	tv.tv_usec = (CONTROL_TIMEOUT_MS % 1000) * 1000;
	setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
	setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
	return fd;
}

static int control_fd(void)
{
	int fd = (int)(intptr_t)pthread_getspecific(control_key) - 1;

	if (fd >= 0)
		return fd;
	if ((fd = control_connect()) < 0)
		return -1;
	pthread_setspecific(control_key, (void *)(intptr_t)(fd + 1));
	return fd;
}

static void control_drop(void)
{
	int fd = (int)(intptr_t)pthread_getspecific(control_key) - 1;
	if (fd >= 0)
		close(fd);
	pthread_setspecific(control_key, NULL);
}

static int io_all(int fd, void *buf, size_t n, int writing)
{
	unsigned char *p = buf;
	while (n > 0) {
		ssize_t k = writing ? write(fd, p, n) : read(fd, p, n);
		if (k > 0) { p += k; n -= (size_t)k; continue; }
		if (k == -1 && errno == EINTR) continue;
		return -1;
	}
	return 0;
}

static ssize_t control_roundtrip(void *ctx, const unsigned char *req, size_t reqlen,
				 unsigned char *rep, size_t repcap)
{
	int fd = control_fd();

	(void)ctx;
	if (fd < 0)
		return -1;
	if (repcap < CCU_REPLY_LEN)
		return -1;
	if (io_all(fd, (void *)(uintptr_t)req, reqlen, 1) != 0 ||
	    io_all(fd, rep, CCU_REPLY_LEN, 0) != 0) {
		/* A half-written request or a truncated reply leaves the stream
		 * out of frame; the only safe repair is a new connection. */
		control_drop();
		return -1;
	}
	return (ssize_t)CCU_REPLY_LEN;
}

/* ── per-request credentials (verbatim from S1; see the header) ─────────── */

static inline void cred_enter(void)
{
	const struct fuse_context *c = fuse_get_context();
	setfsgid(c->gid);
	setfsuid(c->uid);
}

static inline void cred_leave(void)
{
	setfsuid(0);
	setfsgid(0);
}

/* ── routing ────────────────────────────────────────────────────────────── */

static const char *rel(const char *path)
{
	if (path[0] == '/' && path[1] == '\0')
		return ".";
	return path + 1;
}

struct route {
	enum tier   tier;
	int         fd;
	const char *rp;
	/* THE FRAME INTENT THIS ROUTE WAS GIVEN, carried rather than re-derived,
	 * so `tr()` reports the byte the op actually declared. The two ops that
	 * route both ends by hand (`rename`, `link`) used to trace a hand-copied
	 * literal, which happened to be right and would have gone on reporting
	 * the OLD intent the moment either call changed — a confidently wrong
	 * number, which is one level worse than the blind instrument the cflags
	 * field was added to fix.
	 *
	 * NAMED `intent` AND NOT `cflags` for one mechanical reason: the ROUTE
	 * macro's own parameter is called `cflags`, so `r.cflags` inside the
	 * macro body would expand to `r.<the argument>` and not compile. */
	uint8_t     intent;
};

#define SYNTHETIC(t) ((t) == T_SYNTH || (t) == T_BIND)

/*
 * fd -> the tier its open() routed to, and whether that fd was opened for
 * writing. The tier column is the trace's; the writable bit is what makes
 * pt_release able to push a DIRTY frame for exactly the handles that could have
 * changed the file.
 *
 * A plain array indexed by fd, one byte each, written once by the open that
 * produced the fd and read by that fd's own ops. No lock: the kernel does not
 * hand the same fd number to two live handles.
 */
#define FDTIER_SLOTS 65536
static unsigned char fd_tier[FDTIER_SLOTS];
static unsigned char fd_dirty[FDTIER_SLOTS];
/*
 * SEPARATE FROM fd_dirty, and it has to be. `fd_dirty` says "there are bytes to
 * push" and `flush` clears it on a successful reconcile; `fd_claimed` says "cc
 * has stopped caching this path for us", which stays true until the handle
 * closes. Conflating them made `release` skip the only frame that releases the
 * claim whenever a `flush` had already pushed.
 */
static unsigned char fd_claimed[FDTIER_SLOTS];

static void fd_tier_set(int fd, enum tier t, int writable)
{
	if (fd >= 0 && fd < FDTIER_SLOTS) {
		fd_tier[fd] = (unsigned char)t;
		fd_dirty[fd] = (unsigned char)!!writable;
	}
}

/*
 * THE ONE DISPATCH. `fop` is the control frame this op owes cc before the
 * mirror may be touched (0 for an op that owes none); `for_create` routes a
 * path that does not exist yet by its parent, exactly where the instrument did.
 *
 * There is no `default:` arm and there is no host fallback. The switch below is
 * exhaustive over `enum tier`; anything that reaches past it — T_FAIL, and any
 * member a later edit adds — fails closed and says so in the event log.
 *
 * T_FAIL REACHES THAT FALL-THROUGH ONLY FOR A MARKED CALLER now: the
 * caller-sensitive substitution above rewrote it to T_HOST for an unmarked one,
 * so `unpinned-fail-closed` is the marked CLI's reason alone.
 */
/*
 * `cflags` IS THE WHOLE FLAGS BYTE, PASSED THROUGH UNTOUCHED — not a boolean.
 *
 * It was `int for_create` and was forwarded as `for_create ? FOR_CREATE : 0`,
 * which was correct while FOR_CREATE was the only bit. When FOR_WRITE arrived
 * the call sites started handing over a flags byte and this signature went on
 * claiming a boolean, so the collapse silently dropped every other bit: no
 * write claim was ever taken, every guard that depends on one was dead, and a
 * write-only op arrived at cc labelled a create. The parameter is named for
 * what it carries now, because the old name is what hid it.
 */
static int route(const char *op, const char *path, uint8_t cflags, uint8_t fop,
		 struct route *r)
{
	r->rp     = rel(path);
	r->fd     = -1;
	r->intent = cflags;
	r->tier   = resolve_class(path);

	/* THE MARKING EVENT, before tier dispatch: reading the CLI's own binary
	 * is a host-tier op, so a mark set after dispatch would never fire. */
	mark_maybe(path);

	/* THE ONE CALLER-SENSITIVE TIER — policy.h owns the whole decision and the
	 * log row; this only asks. Placed here rather than inside an arm because
	 * the substitution has to happen BEFORE dispatch: the T_HOST arm below is
	 * what gives the substituted route its host fd. The /proc read is paid
	 * only where the answer can differ. */
	if (policy_tier_is_caller_sensitive(r->tier))
		r->tier = policy_caller_tier(op, path, r->tier,
			policy_is_marked_tid((pid_t)fuse_get_context()->pid),
			(pid_t)fuse_get_context()->pid);

	switch (r->tier) {
	case T_HIDE:
		return -ENOENT;

	case T_HOST:
		r->fd = host_fd;
		return 0;

	/* Answered by the caller from the ancestor table — there is no backing
	 * directory, which is the point: these nodes exist so a pinned leaf is
	 * reachable and a bind target exists, and nothing else. */
	case T_BIND:
	case T_SYNTH:
		return 0;

	case T_PROJECT: {
		int rc;
		if (caller_is_self()) {
			/* Liveness, not policy: the one answer that cannot
			 * re-enter this daemon. */
			r->fd = host_fd;
			policy_event(EV_SERVED, op, path, "self-recursion", (pid_t)fuse_get_context()->pid);
			return 0;
		}
		/* THE CWD-CHAIN EXEMPTION — policy.h owns the whole
		 * decision; this only asks and dispatches. */
		if (policy_cwd_exempt(op, path, (pid_t)fuse_get_context()->pid)) {
			r->tier = T_CWD;
			return 0;
		}
		rc = policy_project_route(op, path, (pid_t)fuse_get_context()->pid, fop, cflags);
		if (rc)
			return rc;
		r->fd = remote_fd;      /* no fallback, by design */
		return 0;
	}

	/* T_CWD is derived HERE, by the arm above, and `resolve_class` never
	 * returns it — so reaching this switch with it means a later edit
	 * classified a path as the cwd node outside the exemption, and that
	 * fails closed. Listed alongside T_FAIL rather than defaulted, which
	 * also keeps the switch exhaustive. */
	case T_CWD:
	case T_FAIL:
		break;
	}
	policy_event(EV_DENY, op, path, "unpinned-fail-closed", (pid_t)fuse_get_context()->pid);
	return -ENOENT;
}

#define ROUTE(op, p, cflags, fop)                       \
	struct route r;                                 \
	int rrc = route(op, p, cflags, fop, &r);        \
	if (rrc)                                        \
		return rrc;                             \
	tr(op, p, tier_name(r.tier), r.intent);         \
	const char *rp = r.rp;

/* ── operations ─────────────────────────────────────────────────────────── */

static void *pt_init(struct fuse_conn_info *conn, struct fuse_config *cfg)
{
	(void)conn;
	/* A union must not invent st_ino. The host root and the mirror live on
	 * the same host filesystem, so their inode spaces cannot collide;
	 * synthetic nodes supply their own from the ancestor table, in a range
	 * (SYNTH_INO_BASE) no real filesystem here hands out. */
	cfg->use_ino = 1;
	/* Criterion 7's kernel half. The mount-option half — attr_timeout,
	 * entry_timeout, negative_timeout — is cc's MOUNT_OPTS. */
	cfg->kernel_cache = 0;
	return NULL;
}

static int pt_getattr(const char *path, struct stat *st, struct fuse_file_info *fi)
{
	int rc;
	if (fi && fi->fh) {
		tr("getattr", path, "fh", 0);
		return fstat((int)fi->fh, st) == -1 ? -errno : 0;
	}
	{
		ROUTE("getattr", path, 0, CCU_STAT);
		/* The one op the cwd-chain exemption allows, and the only op
		 * body T_CWD ever reaches.
		 *
		 * BEFORE SYNTHETIC(), AND THE ORDER IS INERT TODAY — SYNTHETIC()
		 * is (T_SYNTH || T_BIND), so it is false for T_CWD and this
		 * branch would still fire after it. It is placed and pinned here
		 * so that WIDENING SYNTHETIC() to include T_CWD cannot silently
		 * start answering this node out of the ancestor table it is
		 * deliberately not in (policy_synth_getattr would find no entry
		 * and answer -ENOENT). */
		if (r.tier == T_CWD)
			return policy_cwd_getattr(path, st);
		if (SYNTHETIC(r.tier))
			return policy_synth_getattr(path, st);
		cred_enter();
		rc = fstatat(r.fd, rp, st, AT_SYMLINK_NOFOLLOW);
		int e = errno;
		cred_leave();
		return rc == -1 ? -e : 0;
	}
}

static int pt_access(const char *path, int mask)
{
	ROUTE("access", path, 0, CCU_STAT);
	/* A synthetic node is 0555 root:root and there is nothing to widen it
	 * to: EROFS on every mutation, so a write probe is a refusal rather than
	 * a permissions question. */
	if (SYNTHETIC(r.tier))
		return (mask & W_OK) ? -EROFS : 0;
	cred_enter();
	int rc = faccessat(r.fd, rp, mask, AT_EACCESS);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_readlink(const char *path, char *buf, size_t size)
{
	ROUTE("readlink", path, 0, CCU_STAT);
	if (SYNTHETIC(r.tier))
		return -EINVAL;         /* a directory is not a symlink */
	cred_enter();
	ssize_t n = readlinkat(r.fd, rp, buf, size - 1);
	int e = errno;
	cred_leave();
	if (n == -1) return -e;
	buf[n] = '\0';
	return 0;
}

/* ── readdir ────────────────────────────────────────────────────────────── */
/*
 * NO MERGE. The instrument merged the remote's listing with the host's because
 * its default tier merged their contents; with the fallback gone there is
 * exactly one source per directory, and a synthetic directory that also listed
 * the host's would be the leak criterion 3 forbids.
 */

struct dirhandle {
	DIR      *d;            /* NULL for a synthetic or bind node */
	enum tier tier;
	char      path[PATH_MAX];
};

static DIR *opendir_at(int dirfd, const char *rp)
{
	int fd = openat(dirfd, rp, O_RDONLY | O_DIRECTORY);
	DIR *d;
	if (fd == -1) return NULL;
	if (!(d = fdopendir(fd))) { int e = errno; close(fd); errno = e; }
	return d;
}

static int pt_opendir(const char *path, struct fuse_file_info *fi)
{
	ROUTE("opendir", path, 0, CCU_LIST);
	struct dirhandle *h;
	int e;

	if (!(h = calloc(1, sizeof(*h))))
		return -ENOMEM;
	snprintf(h->path, sizeof(h->path), "%s", path);
	h->tier = r.tier;

	if (SYNTHETIC(r.tier)) {
		fi->fh = (uint64_t)(uintptr_t)h;
		return 0;
	}
	cred_enter();
	h->d = opendir_at(r.fd, rp);
	e = errno;
	cred_leave();
	if (!h->d) {
		free(h);
		return -(e ? e : ENOENT);
	}
	fi->fh = (uint64_t)(uintptr_t)h;
	return 0;
}

struct fillctx { void *buf; fuse_fill_dir_t filler; int stop; };

static void synth_emit(void *ctx, const char *name, const char *full, enum tier t)
{
	struct fillctx *f = ctx;
	struct stat st;

	if (f->stop)
		return;
	memset(&st, 0, sizeof(st));
	if (SYNTHETIC(t)) {
		/* Its own fixed node, so `ls -l` of a synthetic tree agrees with
		 * a getattr of each child. */
		policy_synth_getattr(full, &st);
	}
	/* A pinned child's kind belongs to the filesystem that backs it and this
	 * listing has not asked; a zero mode is DT_UNKNOWN, which makes the
	 * caller stat the child and get the routed answer. */
	if (f->filler(f->buf, name, &st, 0, 0))
		f->stop = 1;
}

/*
 * The pinned children of ONE directory, collected once per readdir so the
 * dirent loop can mark the ones the mirror already holds and the rest are
 * emitted afterwards. Bounded by the pin list, not by the directory.
 */
#define MAX_PINNED_CHILDREN 64
struct pinned_children {
	char      name[MAX_PINNED_CHILDREN][NAME_MAX + 1];
	char      full[MAX_PINNED_CHILDREN][PATH_MAX];
	enum tier tier[MAX_PINNED_CHILDREN];
	char      seen[MAX_PINNED_CHILDREN];
	size_t    n;
};

static void copy_bounded(char *dst, size_t cap, const char *src)
{
	size_t n = strnlen(src, cap - 1);

	memcpy(dst, src, n);
	dst[n] = '\0';
}

static void pinned_children_collect(void *ctx, const char *name, const char *full, enum tier t)
{
	struct pinned_children *pc = ctx;

	if (pc->n >= MAX_PINNED_CHILDREN) {
		/* AN HONEST BOUND. Silently dropping names would lose them from
		 * `ls` while `stat` kept working — this function's own defect,
		 * at scale. The log is the instrument that would show it. */
		policy_event(EV_SERVED, "readdir", full, "pinned-children-truncated", (pid_t)fuse_get_context()->pid);
		return;
	}
	/* Bounded copies rather than snprintf: both sources are already
	 * PATH_MAX-bounded table entries, but the compiler cannot see that and
	 * its format-truncation analysis is right to say so. */
	copy_bounded(pc->name[pc->n], sizeof(pc->name[0]), name);
	copy_bounded(pc->full[pc->n], sizeof(pc->full[0]), full);
	pc->tier[pc->n] = t;
	pc->seen[pc->n] = 0;
	pc->n++;
}

static void pinned_children_of(const char *dir, struct pinned_children *pc)
{
	pc->n = 0;
	policy_synth_children(dir, pinned_children_collect, pc);
}

static void pinned_children_mark(struct pinned_children *pc, const char *name)
{
	size_t i;

	for (i = 0; i < pc->n; i++)
		if (strcmp(pc->name[i], name) == 0)
			pc->seen[i] = 1;
}

/*
 * EMITTED ONLY IF IT IS REALLY THERE — and this check belongs to REAL
 * directories alone. The asymmetry with `policy_synth_children`, which emits
 * unchecked, is deliberate: H9 forbids a synthetic node from statting the host
 * because a synthetic node HAS no backing directory, and existence is exactly
 * what the ancestor table withholds. A real directory has one, so the check
 * costs nothing H9 protects.
 *
 * Without it every session's `ls /etc` listed `ld.so.preload` and
 * `claude-code` — both ETC_PINS entries, both absent on this host — for `cat`
 * to answer -ENOENT. That is criterion 1's `ls`/`cat` disagreement, which the
 * previous fix reintroduced in the opposite direction.
 *
 * A `host` or `bind` pin is checked against the host root; a `project` child
 * that survived the mark step is not in the mirror and so is not there either.
 */
static void pinned_children_emit(struct pinned_children *pc,
				 void (*emit)(void *, const char *, const char *, enum tier),
				 void *ctx)
{
	struct stat st;
	size_t i;

	for (i = 0; i < pc->n; i++) {
		if (pc->seen[i])
			continue;
		if (pc->tier[i] == T_SYNTH) {
			/* Its own node, from the ancestor table. Nothing to
			 * stat, and H9 says do not try. */
			emit(ctx, pc->name[i], pc->full[i], pc->tier[i]);
			continue;
		}
		if (fstatat(host_fd, rel(pc->full[i]), &st, AT_SYMLINK_NOFOLLOW) == -1)
			continue;
		emit(ctx, pc->name[i], pc->full[i], pc->tier[i]);
	}
}

static int pt_readdir(const char *path, void *buf, fuse_fill_dir_t filler,
		      off_t off, struct fuse_file_info *fi,
		      enum fuse_readdir_flags flags)
{
	(void)off; (void)flags;
	struct dirhandle *h = (struct dirhandle *)(uintptr_t)fi->fh;
	struct dirent *de;

	if (!h->d) {
		struct fillctx fc = { buf, filler, 0 };
		struct stat st;

		memset(&st, 0, sizeof(st));
		policy_synth_getattr(h->path, &st);
		if (filler(buf, ".", &st, 0, 0) || filler(buf, "..", &st, 0, 0))
			return 0;
		policy_synth_children(h->path, synth_emit, &fc);
		return 0;
	}

	/*
	 * PINNED CHILDREN OF A REAL DIRECTORY ARE EMITTED TOO, and this is the
	 * half a round-2 fix removed. cc materialises ONLY `project` content
	 * into the mirror (control.ts `#servable`) — correctly, since a host pin
	 * is served from `host_fd` and a mirror copy of it would be a second copy
	 * of the orchestrator's file inside the run directory, never read. But
	 * the mirror is what this loop reads, so a `host` or `bind` child of a
	 * project directory had no dirent at all while `stat` and `open` on it
	 * kept succeeding: `ls /` omitting `/etc` while `cat /etc/hosts` works is
	 * the same one-caller-two-answers defect as listing a `fail` name, just
	 * inverted. At `mirrorRoot: "/"` that is every pinned path there is.
	 *
	 * The emit rule is policy_synth_children's, applied here as well: host,
	 * project and bind are named; hide and fail are not. Collected FIRST so
	 * the dirent loop can mark the ones already present, and the remainder
	 * emitted after — one small array, no hash set, because a directory's
	 * pinned children are bounded by the pin list and not by the directory.
	 */
	struct pinned_children pc;

	pinned_children_of(h->path, &pc);
	rewinddir(h->d);
	while ((de = readdir(h->d)) != NULL) {
		char  child[PATH_MAX];
		struct stat st;

		if (strcmp(de->d_name, ".") != 0 && strcmp(de->d_name, "..") != 0) {
			snprintf(child, sizeof(child), "%s%s%s",
				 strcmp(path, "/") == 0 ? "" : path, "/", de->d_name);
			/*
			 * WHAT A REAL DIRECTORY MAY NOT LIST, and it is the same
			 * rule policy_synth_children applies to a synthetic one:
			 *   T_HIDE  the mountpoint and the union's own
			 *           scaffolding. Without this the union lists
			 *           its own backing store, and a dirent that
			 *           cannot be stat'd is its own tell.
			 *   T_FAIL  a name whose every op answers -ENOENT.
			 *           Listing it would put `ls` and `cat` in
			 *           disagreement about whether a file exists,
			 *           from one caller — the defect this filesystem
			 *           exists to remove.
			 *
			 * THE SECOND ONE IS BELT AND BRACES, and is stated as
			 * such rather than claimed as the guard: cc's control
			 * server filters an excluded child out of `LIST` before
			 * shaping it (control.ts `#servable`), so the mirror
			 * does not normally hold one for this loop to find.
			 */
			{
				enum tier ct = resolve_class(child);
				if (ct == T_HIDE || ct == T_FAIL)
					continue;
			}
			pinned_children_mark(&pc, de->d_name);
		}
		memset(&st, 0, sizeof(st));
		st.st_ino  = de->d_ino;
		st.st_mode = de->d_type << 12;
		if (filler(buf, de->d_name, &st, 0, 0))
			return 0;
	}

	{
		struct fillctx fc = { buf, filler, 0 };

		pinned_children_emit(&pc, synth_emit, &fc);
	}
	return 0;
}

static int pt_releasedir(const char *path, struct fuse_file_info *fi)
{
	struct dirhandle *h = (struct dirhandle *)(uintptr_t)fi->fh;
	(void)path;
	if (h->d) closedir(h->d);
	free(h);
	return 0;
}

/*
 * TELL cc THE MIRROR IS AUTHORITATIVE AT `path`, and answer with whatever it
 * says. Called after a mutating op has changed the mirror, so the reconcile
 * sees the post-mutation state — including its ABSENCE, which is how an unlink
 * or an rmdir lands.
 *
 * A FAILED RECONCILE FAILS THE OP. The mirror is then ahead of the source and
 * the caller is told so; making that divergence STICKY — refusing every later
 * write to the path until a re-fetch resyncs it — is a separate mechanism and
 * is S3's (docs/architecture.md → "A failed push is loud and sticky"). What
 * this discharges is the weaker, load-bearing half: a project-tier mutation
 * never reports success having landed nowhere.
 */
/*
 * TELL cc THE MIRROR IS AUTHORITATIVE AT `path`, AND SAY WHICH WAY.
 *
 * `removed` is the whole point: cc must never infer a deletion from an absent
 * mirror entry, because the mirror is also its own cache and it removes stale
 * entries itself. An op that removed the entry says so; every other op leaves
 * the bit clear and cc treats a missing entry as ITS OWN failure rather than as
 * the worker's intent.
 *
 * THE RETURN VALUE IS THE OP'S. A reconcile that could not land must not leave
 * the caller thinking it did (epic criterion 10), so every caller returns this.
 */
static int push_mirror_flags(const char *op, const char *path, uint8_t flags)
{
	int rc;

	cache_invalidate(path);
	rc = ccu_call(CCU_DIRTY, flags, path);
	if (rc)
		policy_event(EV_DENY, op, path,
			     (flags & CCU_FLAG_REMOVED) ? "dirty-remove-refused" : "dirty-push-refused",
			     (pid_t)fuse_get_context()->pid);
	return rc;
}

static int push_mirror(const char *op, const char *path, int removed)
{
	return push_mirror_flags(op, path, removed ? CCU_FLAG_REMOVED : 0);
}

/* policy.h owns it — see policy_abandon_claim, which is drivable from the unit
 * fixture because it composes only policy primitives. */
#define abandon_claim(path, tier) policy_abandon_claim((path), (tier))

/*
 * WHAT THE RECONCILE CANNOT EXPRESS, REFUSED RATHER THAN APPLIED TO THE MIRROR
 * ALONE. Its domain is exactly what `RemoteStat` models — file, directory,
 * symlink, absent (src/systems/fuse/remoteSource.ts). Three ops fall outside
 * it, and each would otherwise succeed against the mirror and reach the system
 * never:
 *
 *   mknod   a device, fifo or socket. `localDirSource.stat` already reports
 *           one as absent — there is no faithful mirror representation, and a
 *           regular file standing in for one answers wrongly about what it is.
 *   link    a hard link is an ALIAS, and a reconcile copies. Landing it as a
 *           second independent file would silently break the aliasing the
 *           caller asked for, which is worse than refusing it.
 *   chown   the system's uid/gid space is not the orchestrator's, and choosing
 *           a mapping is a decision S3 owns. No RemoteSource method carries
 *           ownership at all.
 *
 * THE ERRNO IS policy.h's, and it is -EOPNOTSUPP: the truth being told is that
 * this filesystem cannot REPRESENT the operation, and -EPERM would send the
 * caller hunting a privilege that would not change the answer — the same
 * reasoning that chose -EROFS over -EACCES for a synthetic node. `pt_mknod`
 * translates it back to -EPERM at its own call site, because a container
 * refusing a device node is what a caller already expects there and the
 * permissions reading is the right one in that one case.
 */
static int refuse_unreconcilable(const char *op, const char *path, enum tier t)
{
	int rc = policy_unreconcilable(t);

	if (rc)
		policy_event(EV_DENY, op, path, "not-reconcilable", (pid_t)fuse_get_context()->pid);
	return rc;
}

/* An open fd whose METADATA changed still owes a push, and pt_release already
 * sends one for a handle marked dirty — so marking is the whole of it. */
static void fd_mark_dirty(uint64_t fh)
{
	int fd = (int)fh;
	if (fd >= 0 && fd < FDTIER_SLOTS && (enum tier)fd_tier[fd] == T_PROJECT)
		fd_dirty[fd] = 1;
}

/* ── mutations ──────────────────────────────────────────────────────────── */
/*
 * EROFS ON EVERY SYNTHETIC AND BIND NODE, BEFORE ANY FD IS CHOSEN, AND EROFS
 * RATHER THAN EACCES. The node is a read-only scaffold cc derived from the pin
 * list; EACCES would tell the caller a permissions fix exists, and it does not.
 * The instrument's create-lands-on-the-remote-if-the-parent-exists-there arm is
 * exactly the shape this must not fall through to.
 */

static int pt_mkdir(const char *path, mode_t mode)
{
	ROUTE("mkdir", path, CCU_FLAG_FOR_CREATE | CCU_FLAG_FOR_WRITE, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = mkdirat(r.fd, rp, mode);
	int e = errno;
	cred_leave();
	if (rc == -1) { abandon_claim(path, r.tier); return -e; }
	return r.tier == T_PROJECT ? push_mirror("mkdir", path, 0) : 0;
}

static int pt_mknod(const char *path, mode_t mode, dev_t rdev)
{
	ROUTE("mknod", path, CCU_FLAG_FOR_CREATE | CCU_FLAG_FOR_WRITE, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	/* -EPERM here, not the shared -EOPNOTSUPP: see refuse_unreconcilable. */
	if (refuse_unreconcilable("mknod", path, r.tier) != 0) { abandon_claim(path, r.tier); return -EPERM; }
	cred_enter();
	int rc = mknodat(r.fd, rp, mode, rdev);
	int e = errno;
	cred_leave();
	if (rc == -1) { abandon_claim(path, r.tier); return -e; }
	return 0;
}

static int pt_unlink(const char *path)
{
	ROUTE("unlink", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = unlinkat(r.fd, rp, 0);
	int e = errno;
	cred_leave();
	if (rc == -1) { abandon_claim(path, r.tier); return -e; }
	return r.tier == T_PROJECT ? push_mirror("unlink", path, 1) : 0;
}

static int pt_rmdir(const char *path)
{
	ROUTE("rmdir", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = unlinkat(r.fd, rp, AT_REMOVEDIR);
	int e = errno;
	cred_leave();
	if (rc == -1) { abandon_claim(path, r.tier); return -e; }
	return r.tier == T_PROJECT ? push_mirror("rmdir", path, 1) : 0;
}

static int pt_symlink(const char *target, const char *path)
{
	ROUTE("symlink", path, CCU_FLAG_FOR_CREATE | CCU_FLAG_FOR_WRITE, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = symlinkat(target, r.fd, rp);
	int e = errno;
	cred_leave();
	if (rc == -1) { abandon_claim(path, r.tier); return -e; }
	return r.tier == T_PROJECT ? push_mirror("symlink", path, 0) : 0;
}

/*
 * CROSS-TIER RENAME IS -EXDEV, AND THAT IS AN ARCHITECTURE FINDING, NOT A
 * SHORTCUT. renameat2 cannot move a file between two backing stores. S1 §5.3
 * recorded the CLI doing a .claude.json.tmp.<pid>.<rand> write-and-rename in
 * $HOME, which is why the pin is /home/node and not ~/.claude: a pin boundary
 * between a temp file and its rename target produces EXDEV. `mv` masks it by
 * falling back to copy+unlink; a rename(2) caller sees it.
 */
static int pt_rename(const char *from, const char *to, unsigned int flags)
{
	struct route rf, rt;
	int rc;

	if ((rc = route("rename", from, CCU_FLAG_FOR_WRITE, CCU_FETCH, &rf))) return rc;
	if ((rc = route("rename", to, CCU_FLAG_FOR_CREATE | CCU_FLAG_FOR_WRITE, CCU_FETCH, &rt))) {
		abandon_claim(from, rf.tier);
		return rc;
	}
	tr("rename", to, tier_name(rt.tier), rt.intent);
	if ((rc = policy_mutation_check(rf.tier)) || (rc = policy_mutation_check(rt.tier))) goto give_up;
	if (rf.fd != rt.fd) {
		policy_event(EV_DENY, "rename", to, "xdev-rename", (pid_t)fuse_get_context()->pid);
		rc = -EXDEV;
		goto give_up;
	}
	/*
	 * A DIRECTORY RENAME REFUSES, and it is the same reason the reconcile's
	 * removal is non-recursive: `mv dir dir2` is a SUBTREE move, and two
	 * per-path reconciles cannot express it — the from end would `rmdir` a
	 * source directory still holding children the mirror never materialised,
	 * and the to end would create an empty one. Landing it would need a
	 * recursive delete driven by a frame, removing source subtrees the worker
	 * never enumerated. Bash `mv` runs on the system and still works; a
	 * subtree move through the union is S3's if anyone wants it.
	 */
	if (rf.tier == T_PROJECT) {
		struct stat fst;

		if (fstatat(rf.fd, rf.rp, &fst, AT_SYMLINK_NOFOLLOW) == 0 && S_ISDIR(fst.st_mode)) {
			policy_event(EV_DENY, "rename", from, "not-reconcilable", (pid_t)fuse_get_context()->pid);
			rc = -EOPNOTSUPP;
			goto give_up;
		}
	}
	cred_enter();
	rc = renameat2(rf.fd, rf.rp, rt.fd, rt.rp, flags);
	int e = errno;
	cred_leave();
	if (rc == -1) { rc = -e; goto give_up; }
	/* BOTH ENDS, in this order: the source's old entry is now absent from the
	 * mirror and its new one is present, and the reconcile reads each from the
	 * mirror. A same-tier rename is the only kind that reaches here — the
	 * cross-tier case is -EXDEV above. */
	if (rt.tier != T_PROJECT) return 0;
	/* TWO RECONCILES, and the FROM end is a removal — declared, because an
	 * absent mirror entry there is exactly what cc must not read as its own
	 * stale copy. A failure of the second leaves the source holding neither
	 * end; that is recorded in PROVENANCE D13 rather than hidden, and S3
	 * owns making the divergence sticky. */
	if ((rc = push_mirror("rename", from, 1)) != 0) return rc;
	return push_mirror("rename", to, 0);

give_up:
	/* BOTH claims, since both ends took one. */
	abandon_claim(from, rf.tier);
	abandon_claim(to, rt.tier);
	return rc;
}

static int pt_link(const char *from, const char *to)
{
	struct route rf, rt;
	int rc;

	/* `link` REFUSES at the project tier below, so neither end takes a write
	 * claim: a claim nothing releases is a per-path blackhole for the rest of
	 * the session. The `to` end still says FOR_CREATE, which is what makes
	 * the parent exist for a host-tier link. */
	if ((rc = route("link", from, 0, CCU_FETCH, &rf))) return rc;
	if ((rc = route("link", to, CCU_FLAG_FOR_CREATE, CCU_FETCH, &rt))) return rc;
	tr("link", to, tier_name(rt.tier), rt.intent);
	if ((rc = policy_mutation_check(rf.tier)) || (rc = policy_mutation_check(rt.tier))) return rc;
	if ((rc = refuse_unreconcilable("link", to, rt.tier)) != 0) return rc;
	if (rf.fd != rt.fd) {
		policy_event(EV_DENY, "link", to, "xdev-rename", (pid_t)fuse_get_context()->pid);
		return -EXDEV;
	}
	cred_enter();
	rc = linkat(rf.fd, rf.rp, rt.fd, rt.rp, 0);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_chmod(const char *path, mode_t mode, struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		tr("chmod", path, "fh", 0);
		if (fchmod((int)fi->fh, mode) == -1) return -errno;
		fd_mark_dirty(fi->fh);
		return 0;
	}
	{
		ROUTE("chmod", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		cred_enter();
		int rc = fchmodat(r.fd, rp, mode, 0);
		int e = errno;
		cred_leave();
		if (rc == -1) { abandon_claim(path, r.tier); return -e; }
		return r.tier == T_PROJECT ? push_mirror("chmod", path, 0) : 0;
	}
}

static int pt_chown(const char *path, uid_t uid, gid_t gid, struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		int fd = (int)fi->fh;
		tr("chown", path, "fh", 0);
		if (fd >= 0 && fd < FDTIER_SLOTS && (enum tier)fd_tier[fd] == T_PROJECT)
			/* The fh branch took no claim — no FETCH was sent. */
			return refuse_unreconcilable("chown", path, T_PROJECT);
		return fchown(fd, uid, gid) == -1 ? -errno : 0;
	}
	{
		ROUTE("chown", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		if ((rrc = refuse_unreconcilable("chown", path, r.tier)) != 0) { abandon_claim(path, r.tier); return rrc; }
		cred_enter();
		int rc = fchownat(r.fd, rp, uid, gid, AT_SYMLINK_NOFOLLOW);
		int e = errno;
		cred_leave();
		return rc == -1 ? -e : 0;
	}
}

static int pt_truncate(const char *path, off_t size, struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		tr("truncate", path, "fh", 0);
		if (ftruncate((int)fi->fh, size) == -1) return -errno;
		fd_mark_dirty(fi->fh);
		return 0;
	}
	{
		ROUTE("truncate", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		cred_enter();
		int fd = openat(r.fd, rp, O_WRONLY);
		int oe = errno;
		cred_leave();
		if (fd == -1) return -oe;
		int rc = ftruncate(fd, size);
		int e = errno;
		close(fd);
		if (rc == -1) { abandon_claim(path, r.tier); return -e; }
		return r.tier == T_PROJECT ? push_mirror("truncate", path, 0) : 0;
	}
}

static int pt_utimens(const char *path, const struct timespec ts[2],
		      struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		tr("utimens", path, "fh", 0);
		if (futimens((int)fi->fh, ts) == -1) return -errno;
		fd_mark_dirty(fi->fh);
		return 0;
	}
	{
		ROUTE("utimens", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		cred_enter();
		int rc = utimensat(r.fd, rp, ts, AT_SYMLINK_NOFOLLOW);
		int e = errno;
		cred_leave();
		if (rc == -1) { abandon_claim(path, r.tier); return -e; }
		return r.tier == T_PROJECT ? push_mirror("utimens", path, 0) : 0;
	}
}

static int pt_create(const char *path, mode_t mode, struct fuse_file_info *fi)
{
	ROUTE("create", path, CCU_FLAG_FOR_CREATE | CCU_FLAG_FOR_WRITE, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int fd = openat(r.fd, rp, fi->flags | O_CREAT, mode);
	int e = errno;
	cred_leave();
	if (fd == -1) { abandon_claim(path, r.tier); return -e; }
	fd_tier_set(fd, r.tier, 1);
	if (fd < FDTIER_SLOTS) fd_claimed[fd] = 1;
	fi->fh = fd;
	return 0;
}

static int pt_open(const char *path, struct fuse_file_info *fi)
{
	/* A WRITABLE HANDLE TAKES THE CLAIM, a read-only one does not: the claim
	 * turns cc's cache off for this path until the matching DIRTY, and a
	 * reader has no unpushed bytes to protect. */
	ROUTE("open", path, (fi->flags & (O_WRONLY | O_RDWR)) ? CCU_FLAG_FOR_WRITE : 0, CCU_FETCH);
	/* A directory is the only thing a synthetic node ever is. */
	if (SYNTHETIC(r.tier)) return -EISDIR;
	cred_enter();
	int fd = openat(r.fd, rp, fi->flags);
	int e = errno;
	cred_leave();
	if (fd == -1) {
		if (fi->flags & (O_WRONLY | O_RDWR)) abandon_claim(path, r.tier);
		return -e;
	}
	fd_tier_set(fd, r.tier, (fi->flags & (O_WRONLY | O_RDWR)) != 0);
	/* Exactly the handles whose ROUTE carried FOR_WRITE, so the claim cc took
	 * and the claim this daemon releases cannot disagree. */
	if (fd < FDTIER_SLOTS && (fi->flags & (O_WRONLY | O_RDWR)))
		fd_claimed[fd] = 1;
	fi->fh = fd;
	return 0;
}

/* read/write send no frame: the fd is already backed by a materialised file. */
static int pt_read(const char *path, char *buf, size_t size, off_t off,
		   struct fuse_file_info *fi)
{
	ssize_t n;
	(void)path;
	n = pread((int)fi->fh, buf, size, off);
	return n == -1 ? -errno : (int)n;
}

static int pt_write(const char *path, const char *buf, size_t size, off_t off,
		    struct fuse_file_info *fi)
{
	ssize_t n;
	(void)path;
	/* RE-ARM THE PUSH. `flush` clears the bit when its reconcile lands, and a
	 * handle written to again after that owes another one. */
	if ((int)fi->fh >= 0 && (int)fi->fh < FDTIER_SLOTS)
		fd_dirty[(int)fi->fh] = 1;
	n = pwrite((int)fi->fh, buf, size, off);
	return n == -1 ? -errno : (int)n;
}

static int pt_statfs(const char *path, struct statvfs *stbuf)
{
	ROUTE("statfs", path, 0, 0);
	(void)rp;
	/* `df /` must answer, and a synthetic node has no backing store of its
	 * own — every tier but `host` is materialised into the mirror, so that
	 * is the filesystem whose free space the caller is actually consuming. */
	int fd = r.tier == T_HOST ? host_fd : remote_fd;
	return fstatvfs(fd, stbuf) == -1 ? -errno : 0;
}

/*
 * THE PUSH LIVES IN `flush`, NOT IN `release`, AND THAT IS EPIC CRITERION 10.
 *
 * The kernel DISCARDS `release`'s return value — a reconcile that refused there
 * would be logged and nowhere else, and `close()` would return 0 to a worker
 * whose write never reached the system. `flush` is the op whose return value
 * `close(2)` reports, so that is where a failed reconcile has to be answered.
 * The worker sees the errno cc chose, which for a refused DIRTY is **EIO**.
 *
 * `flush` may fire more than once (each `close` of a duplicated descriptor
 * calls it), so the dirty bit is CLEARED by a successful push and SET AGAIN by
 * any later write: one reconcile per batch of writes, each answered to the
 * `close` that triggered it. `release` keeps a push as a backstop for the fd
 * that never saw a flush — a killed process — where there is no `close` left to
 * answer and landing the bytes is the whole of what is owed.
 */
static int pt_flush(const char *path, struct fuse_file_info *fi)
{
	int fd = (int)fi->fh;
	int rc;

	/* The dup/close first, unchanged: it is what reports a write error the
	 * kernel deferred, and it must be answered whatever the tier. */
	int probe = dup(fd);
	if (probe == -1) return -errno;
	if (close(probe) == -1) return -errno;

	if (fd < 0 || fd >= FDTIER_SLOTS || !fd_dirty[fd] ||
	    (enum tier)fd_tier[fd] != T_PROJECT)
		return 0;
	/* KEEPS THE CLAIM. `flush` fires per `close` of a duplicated descriptor
	 * while the original handle stays open, and releasing here left the next
	 * write batch on that handle unprotected — reopening exactly the window
	 * the claim exists to close. `release` is the only releaser. */
	rc = push_mirror_flags("flush", path, CCU_FLAG_FOR_WRITE);
	if (rc == 0)
		fd_dirty[fd] = 0;
	return rc;
}

/*
 * CRITERION 8'S SECOND HALF. A handle that was opened writable pushes DIRTY
 * before it closes, so cc copies the mirror's copy back to the source.
 *
 * READY MEANS CC HAS TAKEN OWNERSHIP OF THE PUSH, NOT THAT THE PUSH LANDED.
 * The awaiting half — a PostToolUse that blocks until it has, and poisons the
 * session if it has not — is 2026-0356's, deliberately (plan 2026-0355 §14).
 *
 * A file written through two handles pushes twice. The push is a full-content
 * copy, so that is idempotent; noted rather than defended against.
 */
static int pt_release(const char *path, struct fuse_file_info *fi)
{
	int fd = (int)fi->fh;

	/*
	 * THE ONLY RELEASER OF THE CLAIM, so this runs for a claimed handle
	 * whether or not anything is dirty — a `flush` that already pushed left
	 * the claim standing deliberately, and nothing else would ever drop it.
	 *
	 * AND IT NO LONGER RE-UPLOADS WHAT `flush` ALREADY LANDED. Against a
	 * local directory the second copy was cheap; against a real transport it
	 * is a second whole-file upload per written file, which is not a
	 * magnitude question (PROVENANCE D13d).
	 *
	 * THE KILLED-PROCESS BACKSTOP IS PRESERVED BY THE CONDITION ITSELF, not
	 * by a second test bolted beside it. A handle whose `flush` never ran —
	 * or whose `flush` refused — still has fd_dirty set, so it sends a FULL
	 * reconcile, which is the whole of what is owed when there is no
	 * `close(2)` left to answer.
	 */
	if (fd >= 0 && fd < FDTIER_SLOTS && fd_claimed[fd] &&
	    (enum tier)fd_tier[fd] == T_PROJECT) {
		push_mirror_flags("release", path,
				  fd_dirty[fd] ? 0 : CCU_FLAG_RELEASE_ONLY);
	}
	if (fd >= 0 && fd < FDTIER_SLOTS) {
		fd_tier[fd] = 0;
		fd_dirty[fd] = 0;
		fd_claimed[fd] = 0;
	}
	close(fd);
	return 0;
}

static int pt_fsync(const char *path, int datasync, struct fuse_file_info *fi)
{
	(void)path;
	int rc = datasync ? fdatasync((int)fi->fh) : fsync((int)fi->fh);
	return rc == -1 ? -errno : 0;
}

static int pt_fallocate(const char *path, int mode, off_t off, off_t len,
			struct fuse_file_info *fi)
{
	(void)path;
	if (fallocate((int)fi->fh, mode, off, len) == -1)
		return -errno;
	/* CONTENT CHANGED, so the handle owes a push. FALLOC_FL_ZERO_RANGE and
	 * FALLOC_FL_PUNCH_HOLE rewrite bytes and a plain fallocate extends the
	 * file, and `flush` clears the bit on a successful reconcile — without
	 * this, `write; flush; fallocate; close` reconciled the pre-fallocate
	 * content and the size change never reached the system. */
	fd_mark_dirty(fi->fh);
	return 0;
}

static off_t pt_lseek(const char *path, off_t off, int whence,
		      struct fuse_file_info *fi)
{
	(void)path;
	off_t rc = lseek((int)fi->fh, off, whence);
	return rc == -1 ? -errno : rc;
}

/* xattr: reported through the routed tier, so a caller that consults them sees
 * the real answer of the tier that owns the file rather than a synthetic
 * ENOTSUP -- and never the other tier's. A synthetic node has no xattrs of its
 * own and must not borrow the host directory's.
 *
 * THE TWO THAT MUTATE ROUTE WITH `FETCH`, NOT `STAT`, and that is not
 * symmetry for its own sake: `FETCH` is where the resolution cache is
 * invalidated, and the rule "every op that can change a file passes that
 * point" is asserted as an ENUMERATION. `setxattr` and `removexattr` read like
 * metadata queries and change the file; `getxattr` and `listxattr` do not. */
static void abspath(const struct route *r, const char *path, char *out, size_t n)
{
	const char *root = (r->fd == remote_fd) ? remote_root : host_root;
	snprintf(out, n, "%s%s", strcmp(root, "/") == 0 ? "" : root, path);
}

static int pt_setxattr(const char *path, const char *name, const char *value,
		       size_t size, int flags)
{
	ROUTE("setxattr", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
	(void)rp;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	if ((rrc = refuse_unreconcilable("setxattr", path, r.tier)) != 0) { abandon_claim(path, r.tier); return rrc; }
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	return lsetxattr(abs, name, value, size, flags) == -1 ? -errno : 0;
}

static int pt_getxattr(const char *path, const char *name, char *value, size_t size)
{
	ROUTE("getxattr", path, 0, CCU_STAT);
	(void)rp;
	/* THE READS REFUSE TOO, and for the mirror's sake rather than the
	 * reconcile's: cc materialises a project path with `copyFile`, which
	 * carries no extended attributes, so the mirror entry has NONE of the
	 * source's. Answering from it would report "no such attribute" about a
	 * file that has one — one path, two answers, in the direction a caller
	 * cannot detect. EOPNOTSUPP is a filesystem's ordinary answer here. */
	if ((rrc = policy_unreconcilable(r.tier))) return rrc;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	ssize_t n = lgetxattr(abs, name, value, size);
	return n == -1 ? -errno : (int)n;
}

static int pt_listxattr(const char *path, char *list, size_t size)
{
	ROUTE("listxattr", path, 0, CCU_STAT);
	(void)rp;
	if ((rrc = policy_unreconcilable(r.tier))) return rrc;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	ssize_t n = llistxattr(abs, list, size);
	return n == -1 ? -errno : (int)n;
}

static int pt_removexattr(const char *path, const char *name)
{
	ROUTE("removexattr", path, CCU_FLAG_FOR_WRITE, CCU_FETCH);
	(void)rp;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	if ((rrc = refuse_unreconcilable("removexattr", path, r.tier)) != 0) { abandon_claim(path, r.tier); return rrc; }
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	return lremovexattr(abs, name) == -1 ? -errno : 0;
}

static const struct fuse_operations pt_ops = {
	.init        = pt_init,
	.getattr     = pt_getattr,
	.access      = pt_access,
	.readlink    = pt_readlink,
	.opendir     = pt_opendir,
	.readdir     = pt_readdir,
	.releasedir  = pt_releasedir,
	.mkdir       = pt_mkdir,
	.mknod       = pt_mknod,
	.unlink      = pt_unlink,
	.rmdir       = pt_rmdir,
	.symlink     = pt_symlink,
	.rename      = pt_rename,
	.link        = pt_link,
	.chmod       = pt_chmod,
	.chown       = pt_chown,
	.truncate    = pt_truncate,
	.utimens     = pt_utimens,
	.create      = pt_create,
	.open        = pt_open,
	.read        = pt_read,
	.write       = pt_write,
	.statfs      = pt_statfs,
	.flush       = pt_flush,
	.release     = pt_release,
	.fsync       = pt_fsync,
	.fallocate   = pt_fallocate,
	.lseek       = pt_lseek,
	.setxattr    = pt_setxattr,
	.getxattr    = pt_getxattr,
	.listxattr   = pt_listxattr,
	.removexattr = pt_removexattr,
};

static void pins_load(const char *file)
{
	FILE *f = fopen(file, "r");
	char  line[PATH_MAX + 64];

	if (!f) {
		fprintf(stderr, "cc-union: pins %s: %s\n", file, strerror(errno));
		exit(1);
	}
	while (fgets(line, sizeof(line), f))
		if (pins_parse_line(line) != 0) {
			fprintf(stderr, "cc-union: pins: %s\n", policy_err);
			exit(1);
		}
	fclose(f);
}

int main(int argc, char *argv[])
{
	const char *hr = getenv("CC_UNION_HOST_ROOT") ?: "/";
	const char *rr = getenv("CC_UNION_REMOTE");
	const char *pf = getenv("CC_UNION_PINS");
	const char *mp = getenv("CC_UNION_MNT");
	const char *tp = getenv("CC_UNION_TRACE");
	const char *fp = getenv("CC_UNION_EVENTS");
	int probe;

	self_tgid     = getpid();
	mark_path     = getenv("CC_UNION_MARK_PATH");
	control_path  = getenv("CC_UNION_CONTROL");
	cwd_path      = getenv("CC_UNION_CWD");

	if (!rr || !pf) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_REMOTE and "
				"CC_UNION_PINS are both required\n");
		return 1;
	}
	/*
	 * THE MARK IS THE PROJECT TIER'S ONLY KEY. Without the marking event
	 * every caller is unmarked and the remote tier is unreachable, so the
	 * mount would serve a silent host-only filesystem that looks exactly
	 * like a containment success. Refuse instead.
	 */
	if (!mark_path) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_MARK_PATH is required; "
				"without it no caller is ever marked and the project tier "
				"is unreachable\n");
		return 1;
	}
	/* Same reasoning for the channel: a daemon that cannot reach cc can
	 * materialise nothing, so every project path would answer -EIO. */
	if (!control_path) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_CONTROL is required; "
				"without cc's control socket no remote path can be "
				"materialised\n");
		return 1;
	}
	/*
	 * THE CWD IS THE PROJECT TIER'S ONLY DOOR FOR AN UNMARKED CALLER, and it
	 * plays the same structural role as the mark path: one input enables the
	 * project tier at all, this one enables ENTRY to it. `policy_cwd_component`
	 * answers 0 for every path when this is NULL, so the chain — the project
	 * root included — would be denied and the bootstrap would die at its `cd`.
	 * A DEFAULT WOULD BE WORSE THAN THE REFUSAL: it would silently un-exempt
	 * the project root and regress card 2026-0373 while looking like it worked.
	 */
	if (!cwd_path) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_CWD is required; "
				"without it no directory component of the CLI's cwd is "
				"exempt and every unmarked spawn dies at its chdir\n");
		return 1;
	}
	/* NORMALISED, NOT NORMALISABLE. cc owns this input (`plan.cwdInside`), so a
	 * non-normalised value is a cc defect; resolving `..` correctly would need
	 * the filesystem, because a component may be a symlink. `buildFusePlan`
	 * asserts the same thing at configuration time. */
	if (!policy_cwd_normalised(cwd_path)) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_CWD=%s is not a normalised "
				"absolute path (no '//', no trailing '/', no '.' or '..' "
				"component)\n", cwd_path);
		return 1;
	}
	if (pthread_key_create(&control_key, control_close) != 0) {
		fprintf(stderr, "cc-union: REFUSED — could not create the control-socket key\n");
		return 1;
	}
	/* Connect once BEFORE mounting. An unconnectable socket discovered on
	 * the first getattr is a mount that came up and answers nothing. */
	if ((probe = control_connect()) < 0) {
		fprintf(stderr, "cc-union: REFUSED — cannot connect to cc's control "
				"socket at %s: %s\n", control_path, strerror(errno));
		return 1;
	}
	close(probe);
	ccu_xport.roundtrip = control_roundtrip;

	snprintf(host_root,   sizeof(host_root),   "%s", hr);
	snprintf(remote_root, sizeof(remote_root), "%s", rr);

	pins_load(pf);
	/* The mountpoint lies inside BOTH roots, so an unguarded union recurses
	 * forever the first time anything walks the tree. S1 §7.5. */
	if (mp && pin_add(T_HIDE, mp) != 0) {
		fprintf(stderr, "cc-union: REFUSED — %s\n", policy_err);
		return 1;
	}
	/* AFTER every pin is in: the ancestor set is derived from the final
	 * table, so the mountpoint's own parents are synthetic too. */
	anc_build();

	if ((host_fd = open(host_root, O_PATH | O_DIRECTORY)) == -1) {
		fprintf(stderr, "cc-union: host root %s: %s\n",
			host_root, strerror(errno));
		return 1;
	}
	if ((remote_fd = open(remote_root, O_PATH | O_DIRECTORY)) == -1) {
		fprintf(stderr, "cc-union: mirror %s: %s\n",
			remote_root, strerror(errno));
		return 1;
	}
	if (tp) {
		if (!(trace_fp = fopen(tp, "a"))) {
			fprintf(stderr, "cc-union: trace %s: %s\n", tp, strerror(errno));
			return 1;
		}
		setvbuf(trace_fp, NULL, _IOLBF, 0);
	}
	if (fp) {
		if (!(event_fp = fopen(fp, "a"))) {
			fprintf(stderr, "cc-union: event log %s: %s\n", fp, strerror(errno));
			return 1;
		}
		setvbuf(event_fp, NULL, _IOLBF, 0);
		/*
		 * THE COLUMNS AND THE ONE CAVEAT, IN THE FILE ITSELF. This log
		 * outlives the run directory (cc harvests it into the store) and
		 * is read by an operator or an agent who has not read
		 * docs/protocol.md. `#` so both parsers skip it.
		 */
		fprintf(event_fp,
			"# cc-union events v2\tkind\top\tpath\treason\tpid\ttgid\tcomm\tcmdline"
			" — identity is sampled at POLICY TIME; the process may have exec'd"
			" since, and comm/cmdline would then name what it became."
			" \\!gone / \\!unreadable / \\!empty / \\!truncated are recorded"
			" absences, not values.\n");
	}

	fprintf(stderr, "cc-union: host=%s mirror=%s pins=%zu synth=%zu "
		"markpath=%s control=%s cwd=%s tgid=%d\n",
		host_root, remote_root, npins, nancs, mark_path, control_path,
		cwd_path, (int)self_tgid);

	umask(0);
	return fuse_main(argc, argv, &pt_ops, NULL);
}
