/*
 * union.c — the FUSE-union daemon cc mounts under a remote-backed worker.
 *
 * ONE POLICY, NOT A MEASUREMENT INSTRUMENT. This file is a fork of the frozen
 * S3 spike instrument `rig/fuse-union-s3.c`, which had three selectable routing
 * modes and eight knobs because its job was to compare them. Every knob is
 * gone; what is left is the single policy the epic specifies. PROVENANCE.md
 * carries the fork point and one row per intentional divergence.
 *
 * ── what it serves, and to whom ─────────────────────────────────────────────
 *
 * A longest-prefix tier table, loaded from $CC_UNION_PINS and generated by
 * src/systems/fuse/tierTable.ts. Five classes reach this file; a sixth is
 * derived (policy.h):
 *
 *   host     the orchestrator's own filesystem, always, for marked and unmarked
 *            callers alike. The CLI's execution closure lives here: its binary,
 *            ld-linux and its shared objects, $HOME, the session scratch dir,
 *            the specific /etc files the runtime needs.
 *   project  the remote tier, and ONLY for a caller marked as the CLI. There is
 *            no host side to fall back to, by design.
 *   bind     a directory bootstrap.sh mounts the ORCHESTRATOR's own over, after
 *            the union is up. Served here as a read-only synthetic node purely
 *            so the bind target exists — /proc, /sys, /dev must never be tiers
 *            (S1 §7.1: a passthrough serving /proc/self/exe answers with the
 *            DAEMON's identity and breaks a bun single-file executable).
 *   hide     ENOENT, and suppressed from the parent's readdir. The union's own
 *            scaffolding, which it must not serve through itself.
 *   fail     ENOENT on both sides, because the system's advertisement excluded
 *            it. Also refused at cc's file-tool seam, so it fails both surfaces.
 *   synth    DERIVED, never written in the pins file: the ancestors of every
 *            pin, so a pinned leaf is reachable without its parents being
 *            served from anywhere. Read-only, fixed attributes.
 *
 * AN UNMATCHED PATH IS `fail`, because T_FAIL is enum index 0 and tier_of
 * returns index 0 for a path no pin matches. The instrument's index 0 was
 * remote-first with a host fallback; that fallback is the "one path, two
 * answers" this architecture exists to remove, and deleting it is why the
 * refusal log below is the instrument the pin list is derived from.
 *
 * ── the caller mark ─────────────────────────────────────────────────────────
 *
 * A thread group is marked the first time it resolves $CC_UNION_MARK_PATH — the
 * CLI's own binary. The mark is sticky, survives exec, is keyed on the TGID and
 * is revalidated against /proc field 22 on every check so a recycled pid cannot
 * inherit it. An UNMARKED caller at a project path gets -ENOENT: never the
 * remote's copy, never the host's. Host-pinned and bind-mounted paths are
 * served to marked and unmarked callers alike. policy.h states the ordering.
 *
 * ── the control channel ─────────────────────────────────────────────────────
 *
 * A unix stream socket at $CC_UNION_CONTROL, one connection per FUSE worker
 * thread, control frames only and never file content (policy.h's codec). No
 * remote-tier op touches the mirror before cc has answered: a bare local stat
 * would report ENOENT for a file that exists remotely and is simply not
 * materialised yet. A wedged cc becomes -EIO on a bounded receive timeout, not
 * an unkillable D state — and never a host fallback, which would look exactly
 * like a containment success.
 *
 * ── zero kernel caching ─────────────────────────────────────────────────────
 *
 * cfg->kernel_cache = 0 here, and attr_timeout/entry_timeout/negative_timeout
 * are all 0 in the mount options cc passes (src/systems/fuse/plan.ts). FUSE's
 * attribute cache is per-inode and this filesystem answers per-caller, so one
 * path measurably answered 15 bytes to `stat` and 33 to `cat` across the
 * routing boundary. policy.h's resolution cache is the caller-aware
 * replacement.
 *
 * ── carried from S1, unchanged ──────────────────────────────────────────────
 *
 * Per-request setfsuid/setfsgid is mandatory, not a tuning knob: S1 §7.2
 * measured that without it the CLI's own Bash tool fails EACCES, because its
 * scratch directory gets created root-owned. Known limit, carried:
 * supplementary groups are NOT switched (setgroups(2) is per-process, not
 * per-thread), so a caller whose access depends on one can be wrongly denied by
 * the daemon-side check. default_permissions means the kernel has already
 * checked the caller's full credentials first, so this is a second gate rather
 * than the only one. It is not equivalent.
 *
 * The self-recursion guard is a LIVENESS precondition, not a routing policy: a
 * caller in the daemon's own thread group must never be served through the
 * remote path, or the daemon blocks on a request only it can answer. Keyed on
 * one tgid, because ancestry — the only key that could describe "the CLI and
 * its children" — is unknowable exactly when it matters (S1 §6 Q2).
 *
 * The trace and the refusal log record PATHS ONLY, never content, so a
 * credential path may appear in them and a credential never does.
 *
 * ── known limit, recorded rather than defended against ──────────────────────
 *
 * A readdir of a `project` directory lists the mirror's children only, so a
 * host pin NESTED inside a project prefix is reachable by name but absent from
 * its parent's listing. It cannot arise at the default mirror root (the
 * project's own remote path); it can at an advertised root of "/". The refusal
 * log is the instrument that would surface it.
 *
 * ── environment ─────────────────────────────────────────────────────────────
 *
 *   CC_UNION_HOST_ROOT   host tier root                       (default "/")
 *   CC_UNION_REMOTE      the per-session mirror directory     (required)
 *   CC_UNION_PINS        the tier table file                  (required)
 *   CC_UNION_CONTROL     cc's control socket                  (required)
 *   CC_UNION_MARK_PATH   the path whose resolution marks a thread group
 *                                                             (required)
 *   CC_UNION_MNT         the mountpoint, hidden implicitly (recursion guard)
 *   CC_UNION_TRACE       every path the kernel asks about, with caller identity
 *   CC_UNION_REFUSALS    the refusal log — the instrument the pin list is
 *                        derived from, and the thing that must be empty by the
 *                        end
 */
#define FUSE_USE_VERSION 31
#define _GNU_SOURCE

#include <fuse.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <fcntl.h>
#include <dirent.h>
#include <pthread.h>
#include <limits.h>
#include <stdint.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/un.h>
#include <sys/xattr.h>
#include <sys/time.h>
#include <sys/fsuid.h>

#include "policy.h"

static int   host_fd = -1, remote_fd = -1;
static char  host_root[PATH_MAX]   = "/";
static char  remote_root[PATH_MAX] = "";
static pid_t self_tgid = 0;
static const char *mark_path = NULL;

/* ── caller identity, for the trace ─────────────────────────────────────── */
/*
 * pid -> (tgid, ppid, starttime, exe, cmdline), cached; a thread's tgid is
 * fixed for its life. comm is NOT cached and never will be: S1 §8.2 defect 2
 * cached it and every request from the CLI came back labelled comm=bash,
 * because the pid was first seen as the shell that later exec'd into the CLI.
 *
 * TGID AND STARTTIME COME FROM policy.h's READER, not from a second parse here:
 * the policy routes on them and the trace attributes on them, and two readers
 * of /proc for one fact is how they come to disagree.
 */
#define PCACHE_SLOTS 8192
struct pent {
	pid_t         pid, tgid, ppid;
	unsigned long long start;   /* /proc/<pid>/stat field 22 */
	char          exe[192];     /* resolved once, per pid */
	char          cmd[192];     /* full cmdline, NULs -> spaces */
};
static struct pent     pcache[PCACHE_SLOTS];
static pthread_mutex_t pcache_mu = PTHREAD_MUTEX_INITIALIZER;

static void read_exe(pid_t pid, char *out, size_t n)
{
	char buf[64];
	ssize_t r;

	snprintf(buf, sizeof(buf), "/proc/%d/exe", (int)pid);
	if ((r = readlink(buf, out, n - 1)) > 0) {
		out[r] = '\0';
		return;
	}
	/*
	 * /proc/<tgid>/exe is rendered by d_path against the READER's root. The
	 * daemon lives outside the chroot the callers live in, so the link can
	 * come back unreachable; the trace records "<unreadable>" rather than
	 * silently substituting the cmdline, because a column that means two
	 * different things in one file is worse than a gap.
	 */
	snprintf(out, n, "<unreadable>");
}

/*
 * THE COLUMN THAT ACTUALLY ATTRIBUTES AN OP. exe is the INTERPRETER for
 * anything script-shaped: a PreToolUse hook and the Bash forwarder are both
 * /bin/bash, and telling them apart is the entire containment question. The
 * kernel builds argv for a shebang script as [interpreter, script, args...],
 * so the script's own path is in the cmdline and nowhere else.
 */
static void read_cmdline(pid_t pid, char *out, size_t n)
{
	char buf[64];
	int f;
	ssize_t k, i;

	snprintf(out, n, "<gone>");
	snprintf(buf, sizeof(buf), "/proc/%d/cmdline", (int)pid);
	if ((f = open(buf, O_RDONLY)) == -1)
		return;
	k = read(f, out, n - 1);
	close(f);
	if (k <= 0) {
		snprintf(out, n, "<gone>");
		return;
	}
	out[k] = '\0';
	/*
	 * NULs become spaces -- and so does EVERY other control character. A
	 * `bash -c` cmdline carries the whole script, newlines included, and an
	 * embedded newline splits one trace row into many: the first version of
	 * this instrument produced 1662 unparsable rows out of ~3000 for exactly
	 * that reason, and the analysis silently dropped them.
	 */
	for (i = 0; i < k; i++)
		if ((unsigned char)out[i] < 0x20 || (unsigned char)out[i] == 0x7f)
			out[i] = ' ';
	while (k > 0 && out[k - 1] == ' ')
		out[--k] = '\0';
}

/*
 * Resolve TID -> (TGID, PPID, starttime, exe, cmdline). The entry is
 * REVALIDATED on every hit, unconditionally: the instrument made that a flag so
 * the cost could be measured, and the unvalidated arm was the unsound half. A
 * recycled pid otherwise returns its predecessor's tgid for the life of the
 * daemon, and exec(2) replaces the cmdline and the exe link while leaving pid,
 * tgid and start time untouched — so both the start-time compare and the
 * re-read below are load-bearing, and neither can substitute for the other.
 */
static void resolve_ids(pid_t pid, pid_t *tgid_out, pid_t *ppid_out,
			unsigned long long *start_out, const char **exe_out,
			const char **cmd_out)
{
	size_t slot = ((size_t)pid * 2654435761u) % PCACHE_SLOTS;
	pid_t tgid = -1, ppid = -1;
	unsigned long long start = 0;
	const char *exe = "<gone>", *cmd = "<gone>";
	size_t i;

	pthread_mutex_lock(&pcache_mu);
	for (i = 0; i < 64; i++) {
		struct pent *e = &pcache[(slot + i) % PCACHE_SLOTS];
		if (e->pid == pid) {
			unsigned long long now = policy_proc.starttime(pid);
			if (now != e->start) {
				e->pid = 0;   /* recycled: refill below */
				i--;
				continue;
			}
			read_exe(e->tgid > 0 ? e->tgid : pid, e->exe, sizeof(e->exe));
			read_cmdline(e->tgid > 0 ? e->tgid : pid, e->cmd, sizeof(e->cmd));
			tgid = e->tgid; ppid = e->ppid;
			start = e->start; exe = e->exe; cmd = e->cmd;
			break;
		}
		if (e->pid == 0) {
			char buf[64];
			FILE *f;

			e->pid = pid; e->tgid = policy_proc.tgid(pid); e->ppid = -1;
			e->start = 0; e->exe[0] = '\0';
			snprintf(buf, sizeof(buf), "/proc/%d/status", (int)pid);
			if ((f = fopen(buf, "r")) != NULL) {
				char line[256];
				while (fgets(line, sizeof(line), f))
					if (strncmp(line, "PPid:", 5) == 0) {
						e->ppid = (pid_t)atoi(line + 5);
						break;
					}
				fclose(f);
			}
			e->start = policy_proc.starttime(pid);
			read_exe(e->tgid > 0 ? e->tgid : pid, e->exe, sizeof(e->exe));
			read_cmdline(e->tgid > 0 ? e->tgid : pid, e->cmd, sizeof(e->cmd));
			tgid = e->tgid; ppid = e->ppid;
			start = e->start; exe = e->exe; cmd = e->cmd;
			break;
		}
	}
	pthread_mutex_unlock(&pcache_mu);
	*tgid_out  = tgid;
	*ppid_out  = ppid;
	if (start_out) *start_out = start;
	if (exe_out)   *exe_out   = exe;
	if (cmd_out)   *cmd_out   = cmd;
}

static void read_comm(pid_t pid, char *out, size_t n)
{
	char buf[64];
	FILE *f;

	snprintf(out, n, "<gone>");
	snprintf(buf, sizeof(buf), "/proc/%d/comm", (int)pid);
	if ((f = fopen(buf, "r")) != NULL) {
		if (fgets(out, n, f)) {
			char *nl = strchr(out, '\n');
			if (nl) *nl = '\0';
		}
		fclose(f);
	}
}

/*
 * THE self-recursion guard. Not a routing policy -- a liveness precondition.
 * It is the minimum possible key (one tgid) and needs no ancestry walk. Where
 * it fires the path is served from the HOST, which is the one answer that
 * cannot re-enter this daemon.
 */
static int caller_is_self(void)
{
	const struct fuse_context *c = fuse_get_context();

	if ((pid_t)c->pid == self_tgid)
		return 1;
	return policy_proc.tgid((pid_t)c->pid) == self_tgid;
}

/* THE MARKING EVENT, on every routed path. S1 §9.1 measured that this is NOT
 * the marked process's first op: it is the shell that later execs into the CLI,
 * and it does real work first. That window is a property of the launcher. */
static void mark_maybe(const char *path)
{
	if (!mark_path || strcmp(path, mark_path) != 0)
		return;
	policy_mark_tid((pid_t)fuse_get_context()->pid);
}

/* ── trace ──────────────────────────────────────────────────────────────── */

static FILE           *trace_fp = NULL;
static pthread_mutex_t trace_mu = PTHREAD_MUTEX_INITIALIZER;

static void tr(const char *op, const char *path, const char *tier)
{
	const struct fuse_context *ctx;
	char comm[24];
	const char *exe, *cmd;
	pid_t tgid, ppid;
	unsigned long long start;

	if (!trace_fp)
		return;
	ctx = fuse_get_context();
	resolve_ids((pid_t)ctx->pid, &tgid, &ppid, &start, &exe, &cmd);
	read_comm((pid_t)ctx->pid, comm, sizeof(comm));

	pthread_mutex_lock(&trace_mu);
	fprintf(trace_fp,
		"%s\t%s\ttier=%s pid=%d uid=%d gid=%d tgid=%d ppid=%d "
		"comm=%s mark=%d exe=%s cmd=%s\n",
		op, path, tier, (int)ctx->pid, (int)ctx->uid,
		(int)ctx->gid, (int)tgid, (int)ppid, comm, mark_of(tgid), exe, cmd);
	pthread_mutex_unlock(&trace_mu);
}

/* ── the control channel's transport ────────────────────────────────────── */
/*
 * ONE CONNECTION PER FUSE WORKER THREAD, opened lazily and held in a
 * pthread_key with a destructor, so a request never waits on another thread's
 * reply and a retired thread does not leak its fd. Blocking per request, as the
 * epic licenses.
 *
 * SO_RCVTIMEO IS THE WHOLE LIVENESS ARGUMENT: without it a cc that stops
 * answering leaves the calling thread in an uninterruptible FUSE wait, and the
 * mount can only be recovered by aborting the connection. With it the op fails
 * -EIO, the daemon logs a refusal, and teardown proceeds normally.
 */
#define CONTROL_TIMEOUT_MS 120000

static const char *control_path = NULL;
static pthread_key_t control_key;

/* Stored as fd+1, so a live fd 0 is distinguishable from "no connection" and
 * the key's destructor actually runs (pthread_setspecific(NULL) suppresses it). */
static void control_close(void *v)
{
	int fd = (int)(intptr_t)v - 1;
	if (fd >= 0)
		close(fd);
}

static int control_connect(void)
{
	struct sockaddr_un sa;
	struct timeval tv;
	int fd;

	if (!control_path || strlen(control_path) >= sizeof(sa.sun_path))
		return -1;
	if ((fd = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0)) == -1)
		return -1;
	memset(&sa, 0, sizeof(sa));
	sa.sun_family = AF_UNIX;
	snprintf(sa.sun_path, sizeof(sa.sun_path), "%s", control_path);
	if (connect(fd, (struct sockaddr *)&sa, sizeof(sa)) == -1) {
		close(fd);
		return -1;
	}
	tv.tv_sec  = CONTROL_TIMEOUT_MS / 1000;
	tv.tv_usec = (CONTROL_TIMEOUT_MS % 1000) * 1000;
	setsockopt(fd, SOL_SOCKET, SO_RCVTIMEO, &tv, sizeof(tv));
	setsockopt(fd, SOL_SOCKET, SO_SNDTIMEO, &tv, sizeof(tv));
	return fd;
}

static int control_fd(void)
{
	int fd = (int)(intptr_t)pthread_getspecific(control_key) - 1;

	if (fd >= 0)
		return fd;
	if ((fd = control_connect()) < 0)
		return -1;
	pthread_setspecific(control_key, (void *)(intptr_t)(fd + 1));
	return fd;
}

static void control_drop(void)
{
	int fd = (int)(intptr_t)pthread_getspecific(control_key) - 1;
	if (fd >= 0)
		close(fd);
	pthread_setspecific(control_key, NULL);
}

static int io_all(int fd, void *buf, size_t n, int writing)
{
	unsigned char *p = buf;
	while (n > 0) {
		ssize_t k = writing ? write(fd, p, n) : read(fd, p, n);
		if (k > 0) { p += k; n -= (size_t)k; continue; }
		if (k == -1 && errno == EINTR) continue;
		return -1;
	}
	return 0;
}

static ssize_t control_roundtrip(void *ctx, const unsigned char *req, size_t reqlen,
				 unsigned char *rep, size_t repcap)
{
	int fd = control_fd();

	(void)ctx;
	if (fd < 0)
		return -1;
	if (repcap < CCU_REPLY_LEN)
		return -1;
	if (io_all(fd, (void *)(uintptr_t)req, reqlen, 1) != 0 ||
	    io_all(fd, rep, CCU_REPLY_LEN, 0) != 0) {
		/* A half-written request or a truncated reply leaves the stream
		 * out of frame; the only safe repair is a new connection. */
		control_drop();
		return -1;
	}
	return (ssize_t)CCU_REPLY_LEN;
}

/* ── per-request credentials (verbatim from S1; see the header) ─────────── */

static inline void cred_enter(void)
{
	const struct fuse_context *c = fuse_get_context();
	setfsgid(c->gid);
	setfsuid(c->uid);
}

static inline void cred_leave(void)
{
	setfsuid(0);
	setfsgid(0);
}

/* ── routing ────────────────────────────────────────────────────────────── */

static const char *rel(const char *path)
{
	if (path[0] == '/' && path[1] == '\0')
		return ".";
	return path + 1;
}

struct route {
	enum tier   tier;
	int         fd;
	const char *rp;
};

#define SYNTHETIC(t) ((t) == T_SYNTH || (t) == T_BIND)

/*
 * fd -> the tier its open() routed to, and whether that fd was opened for
 * writing. The tier column is the trace's; the writable bit is what makes
 * pt_release able to push a DIRTY frame for exactly the handles that could have
 * changed the file.
 *
 * A plain array indexed by fd, one byte each, written once by the open that
 * produced the fd and read by that fd's own ops. No lock: the kernel does not
 * hand the same fd number to two live handles.
 */
#define FDTIER_SLOTS 65536
static unsigned char fd_tier[FDTIER_SLOTS];
static unsigned char fd_dirty[FDTIER_SLOTS];

static void fd_tier_set(int fd, enum tier t, int writable)
{
	if (fd >= 0 && fd < FDTIER_SLOTS) {
		fd_tier[fd] = (unsigned char)t;
		fd_dirty[fd] = (unsigned char)!!writable;
	}
}

/*
 * THE ONE DISPATCH. `fop` is the control frame this op owes cc before the
 * mirror may be touched (0 for an op that owes none); `for_create` routes a
 * path that does not exist yet by its parent, exactly where the instrument did.
 *
 * There is no `default:` arm and there is no host fallback. The switch below is
 * exhaustive over `enum tier`; anything that reaches past it — T_FAIL, and any
 * member a later edit adds — fails closed and says so in the refusal log.
 */
static int route(const char *op, const char *path, int for_create, uint8_t fop,
		 struct route *r)
{
	r->rp   = rel(path);
	r->fd   = -1;
	r->tier = resolve_class(path);

	/* THE MARKING EVENT, before tier dispatch: reading the CLI's own binary
	 * is a host-tier op, so a mark set after dispatch would never fire. */
	mark_maybe(path);

	switch (r->tier) {
	case T_HIDE:
		return -ENOENT;

	case T_HOST:
		r->fd = host_fd;
		return 0;

	/* Answered by the caller from the ancestor table — there is no backing
	 * directory, which is the point: these nodes exist so a pinned leaf is
	 * reachable and a bind target exists, and nothing else. */
	case T_BIND:
	case T_SYNTH:
		return 0;

	case T_PROJECT: {
		int rc;
		if (caller_is_self()) {
			/* Liveness, not policy: the one answer that cannot
			 * re-enter this daemon. */
			r->fd = host_fd;
			policy_refuse(op, path, "self-recursion");
			return 0;
		}
		rc = policy_project_route(op, path, (pid_t)fuse_get_context()->pid, fop,
					  for_create ? CCU_FLAG_FOR_CREATE : 0);
		if (rc)
			return rc;
		r->fd = remote_fd;      /* no fallback, by design */
		return 0;
	}

	case T_FAIL:
		break;
	}
	policy_refuse(op, path, "unpinned-fail-closed");
	return -ENOENT;
}

#define ROUTE(op, p, create, fop)                       \
	struct route r;                                 \
	int rrc = route(op, p, create, fop, &r);        \
	if (rrc)                                        \
		return rrc;                             \
	tr(op, p, tier_name(r.tier));                   \
	const char *rp = r.rp;

/* ── operations ─────────────────────────────────────────────────────────── */

static void *pt_init(struct fuse_conn_info *conn, struct fuse_config *cfg)
{
	(void)conn;
	/* A union must not invent st_ino. The host root and the mirror live on
	 * the same host filesystem, so their inode spaces cannot collide;
	 * synthetic nodes supply their own from the ancestor table, in a range
	 * (SYNTH_INO_BASE) no real filesystem here hands out. */
	cfg->use_ino = 1;
	/* Criterion 7's kernel half. The mount-option half — attr_timeout,
	 * entry_timeout, negative_timeout — is cc's MOUNT_OPTS. */
	cfg->kernel_cache = 0;
	return NULL;
}

static int pt_getattr(const char *path, struct stat *st, struct fuse_file_info *fi)
{
	int rc;
	if (fi && fi->fh) {
		tr("getattr", path, "fh");
		return fstat((int)fi->fh, st) == -1 ? -errno : 0;
	}
	{
		ROUTE("getattr", path, 0, CCU_STAT);
		if (SYNTHETIC(r.tier))
			return policy_synth_getattr(path, st);
		cred_enter();
		rc = fstatat(r.fd, rp, st, AT_SYMLINK_NOFOLLOW);
		int e = errno;
		cred_leave();
		return rc == -1 ? -e : 0;
	}
}

static int pt_access(const char *path, int mask)
{
	ROUTE("access", path, 0, CCU_STAT);
	/* A synthetic node is 0555 root:root and there is nothing to widen it
	 * to: EROFS on every mutation, so a write probe is a refusal rather than
	 * a permissions question. */
	if (SYNTHETIC(r.tier))
		return (mask & W_OK) ? -EROFS : 0;
	cred_enter();
	int rc = faccessat(r.fd, rp, mask, AT_EACCESS);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_readlink(const char *path, char *buf, size_t size)
{
	ROUTE("readlink", path, 0, CCU_STAT);
	if (SYNTHETIC(r.tier))
		return -EINVAL;         /* a directory is not a symlink */
	cred_enter();
	ssize_t n = readlinkat(r.fd, rp, buf, size - 1);
	int e = errno;
	cred_leave();
	if (n == -1) return -e;
	buf[n] = '\0';
	return 0;
}

/* ── readdir ────────────────────────────────────────────────────────────── */
/*
 * NO MERGE. The instrument merged the remote's listing with the host's because
 * its default tier merged their contents; with the fallback gone there is
 * exactly one source per directory, and a synthetic directory that also listed
 * the host's would be the leak criterion 3 forbids.
 */

struct dirhandle {
	DIR      *d;            /* NULL for a synthetic or bind node */
	enum tier tier;
	char      path[PATH_MAX];
};

static DIR *opendir_at(int dirfd, const char *rp)
{
	int fd = openat(dirfd, rp, O_RDONLY | O_DIRECTORY);
	DIR *d;
	if (fd == -1) return NULL;
	if (!(d = fdopendir(fd))) { int e = errno; close(fd); errno = e; }
	return d;
}

static int pt_opendir(const char *path, struct fuse_file_info *fi)
{
	ROUTE("opendir", path, 0, CCU_LIST);
	struct dirhandle *h;
	int e;

	if (!(h = calloc(1, sizeof(*h))))
		return -ENOMEM;
	snprintf(h->path, sizeof(h->path), "%s", path);
	h->tier = r.tier;

	if (SYNTHETIC(r.tier)) {
		fi->fh = (uint64_t)(uintptr_t)h;
		return 0;
	}
	cred_enter();
	h->d = opendir_at(r.fd, rp);
	e = errno;
	cred_leave();
	if (!h->d) {
		free(h);
		return -(e ? e : ENOENT);
	}
	fi->fh = (uint64_t)(uintptr_t)h;
	return 0;
}

struct fillctx { void *buf; fuse_fill_dir_t filler; int stop; };

static void synth_emit(void *ctx, const char *name, const char *full, enum tier t)
{
	struct fillctx *f = ctx;
	struct stat st;

	if (f->stop)
		return;
	memset(&st, 0, sizeof(st));
	if (SYNTHETIC(t)) {
		/* Its own fixed node, so `ls -l` of a synthetic tree agrees with
		 * a getattr of each child. */
		policy_synth_getattr(full, &st);
	}
	/* A pinned child's kind belongs to the filesystem that backs it and this
	 * listing has not asked; a zero mode is DT_UNKNOWN, which makes the
	 * caller stat the child and get the routed answer. */
	if (f->filler(f->buf, name, &st, 0, 0))
		f->stop = 1;
}

static int pt_readdir(const char *path, void *buf, fuse_fill_dir_t filler,
		      off_t off, struct fuse_file_info *fi,
		      enum fuse_readdir_flags flags)
{
	(void)off; (void)flags;
	struct dirhandle *h = (struct dirhandle *)(uintptr_t)fi->fh;
	struct dirent *de;

	if (!h->d) {
		struct fillctx fc = { buf, filler, 0 };
		struct stat st;

		memset(&st, 0, sizeof(st));
		policy_synth_getattr(h->path, &st);
		if (filler(buf, ".", &st, 0, 0) || filler(buf, "..", &st, 0, 0))
			return 0;
		policy_synth_children(h->path, synth_emit, &fc);
		return 0;
	}

	rewinddir(h->d);
	while ((de = readdir(h->d)) != NULL) {
		char  child[PATH_MAX];
		struct stat st;

		if (strcmp(de->d_name, ".") != 0 && strcmp(de->d_name, "..") != 0) {
			snprintf(child, sizeof(child), "%s%s%s",
				 strcmp(path, "/") == 0 ? "" : path, "/", de->d_name);
			/* the mountpoint and the union's own scaffolding. Without
			 * this the union lists its own backing store, and a
			 * dirent that cannot be stat'd is its own tell. */
			if (tier_of(child) == T_HIDE)
				continue;
		}
		memset(&st, 0, sizeof(st));
		st.st_ino  = de->d_ino;
		st.st_mode = de->d_type << 12;
		if (filler(buf, de->d_name, &st, 0, 0))
			break;
	}
	return 0;
}

static int pt_releasedir(const char *path, struct fuse_file_info *fi)
{
	struct dirhandle *h = (struct dirhandle *)(uintptr_t)fi->fh;
	(void)path;
	if (h->d) closedir(h->d);
	free(h);
	return 0;
}

/* ── mutations ──────────────────────────────────────────────────────────── */
/*
 * EROFS ON EVERY SYNTHETIC AND BIND NODE, BEFORE ANY FD IS CHOSEN, AND EROFS
 * RATHER THAN EACCES. The node is a read-only scaffold cc derived from the pin
 * list; EACCES would tell the caller a permissions fix exists, and it does not.
 * The instrument's create-lands-on-the-remote-if-the-parent-exists-there arm is
 * exactly the shape this must not fall through to.
 */

static int pt_mkdir(const char *path, mode_t mode)
{
	ROUTE("mkdir", path, 1, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = mkdirat(r.fd, rp, mode);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_mknod(const char *path, mode_t mode, dev_t rdev)
{
	ROUTE("mknod", path, 1, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = mknodat(r.fd, rp, mode, rdev);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_unlink(const char *path)
{
	ROUTE("unlink", path, 0, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = unlinkat(r.fd, rp, 0);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_rmdir(const char *path)
{
	ROUTE("rmdir", path, 0, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = unlinkat(r.fd, rp, AT_REMOVEDIR);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_symlink(const char *target, const char *path)
{
	ROUTE("symlink", path, 1, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int rc = symlinkat(target, r.fd, rp);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

/*
 * CROSS-TIER RENAME IS -EXDEV, AND THAT IS AN ARCHITECTURE FINDING, NOT A
 * SHORTCUT. renameat2 cannot move a file between two backing stores. S1 §5.3
 * recorded the CLI doing a .claude.json.tmp.<pid>.<rand> write-and-rename in
 * $HOME, which is why the pin is /home/node and not ~/.claude: a pin boundary
 * between a temp file and its rename target produces EXDEV. `mv` masks it by
 * falling back to copy+unlink; a rename(2) caller sees it.
 */
static int pt_rename(const char *from, const char *to, unsigned int flags)
{
	struct route rf, rt;
	int rc;

	if ((rc = route("rename", from, 0, CCU_FETCH, &rf))) return rc;
	if ((rc = route("rename", to,   1, CCU_FETCH, &rt))) return rc;
	tr("rename", to, tier_name(rt.tier));
	if ((rc = policy_mutation_check(rf.tier)) || (rc = policy_mutation_check(rt.tier))) return rc;
	if (rf.fd != rt.fd) {
		policy_refuse("rename", to, "xdev-rename");
		return -EXDEV;
	}
	cred_enter();
	rc = renameat2(rf.fd, rf.rp, rt.fd, rt.rp, flags);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_link(const char *from, const char *to)
{
	struct route rf, rt;
	int rc;

	if ((rc = route("link", from, 0, CCU_FETCH, &rf))) return rc;
	if ((rc = route("link", to,   1, CCU_FETCH, &rt))) return rc;
	tr("link", to, tier_name(rt.tier));
	if ((rc = policy_mutation_check(rf.tier)) || (rc = policy_mutation_check(rt.tier))) return rc;
	if (rf.fd != rt.fd) {
		policy_refuse("link", to, "xdev-rename");
		return -EXDEV;
	}
	cred_enter();
	rc = linkat(rf.fd, rf.rp, rt.fd, rt.rp, 0);
	int e = errno;
	cred_leave();
	return rc == -1 ? -e : 0;
}

static int pt_chmod(const char *path, mode_t mode, struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		tr("chmod", path, "fh");
		return fchmod((int)fi->fh, mode) == -1 ? -errno : 0;
	}
	{
		ROUTE("chmod", path, 0, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		cred_enter();
		int rc = fchmodat(r.fd, rp, mode, 0);
		int e = errno;
		cred_leave();
		return rc == -1 ? -e : 0;
	}
}

static int pt_chown(const char *path, uid_t uid, gid_t gid, struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		tr("chown", path, "fh");
		return fchown((int)fi->fh, uid, gid) == -1 ? -errno : 0;
	}
	{
		ROUTE("chown", path, 0, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		cred_enter();
		int rc = fchownat(r.fd, rp, uid, gid, AT_SYMLINK_NOFOLLOW);
		int e = errno;
		cred_leave();
		return rc == -1 ? -e : 0;
	}
}

static int pt_truncate(const char *path, off_t size, struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		tr("truncate", path, "fh");
		return ftruncate((int)fi->fh, size) == -1 ? -errno : 0;
	}
	{
		ROUTE("truncate", path, 0, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		cred_enter();
		int fd = openat(r.fd, rp, O_WRONLY);
		int oe = errno;
		cred_leave();
		if (fd == -1) return -oe;
		int rc = ftruncate(fd, size);
		int e = errno;
		close(fd);
		return rc == -1 ? -e : 0;
	}
}

static int pt_utimens(const char *path, const struct timespec ts[2],
		      struct fuse_file_info *fi)
{
	if (fi && fi->fh) {
		tr("utimens", path, "fh");
		return futimens((int)fi->fh, ts) == -1 ? -errno : 0;
	}
	{
		ROUTE("utimens", path, 0, CCU_FETCH);
		if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
		cred_enter();
		int rc = utimensat(r.fd, rp, ts, AT_SYMLINK_NOFOLLOW);
		int e = errno;
		cred_leave();
		return rc == -1 ? -e : 0;
	}
}

static int pt_create(const char *path, mode_t mode, struct fuse_file_info *fi)
{
	ROUTE("create", path, 1, CCU_FETCH);
	if ((rrc = policy_mutation_check(r.tier)) != 0) return rrc;
	cred_enter();
	int fd = openat(r.fd, rp, fi->flags | O_CREAT, mode);
	int e = errno;
	cred_leave();
	if (fd == -1) return -e;
	fd_tier_set(fd, r.tier, 1);
	fi->fh = fd;
	return 0;
}

static int pt_open(const char *path, struct fuse_file_info *fi)
{
	ROUTE("open", path, 0, CCU_FETCH);
	/* A directory is the only thing a synthetic node ever is. */
	if (SYNTHETIC(r.tier)) return -EISDIR;
	cred_enter();
	int fd = openat(r.fd, rp, fi->flags);
	int e = errno;
	cred_leave();
	if (fd == -1) return -e;
	fd_tier_set(fd, r.tier, (fi->flags & (O_WRONLY | O_RDWR)) != 0);
	fi->fh = fd;
	return 0;
}

/* read/write send no frame: the fd is already backed by a materialised file. */
static int pt_read(const char *path, char *buf, size_t size, off_t off,
		   struct fuse_file_info *fi)
{
	ssize_t n;
	(void)path;
	n = pread((int)fi->fh, buf, size, off);
	return n == -1 ? -errno : (int)n;
}

static int pt_write(const char *path, const char *buf, size_t size, off_t off,
		    struct fuse_file_info *fi)
{
	ssize_t n;
	(void)path;
	n = pwrite((int)fi->fh, buf, size, off);
	return n == -1 ? -errno : (int)n;
}

static int pt_statfs(const char *path, struct statvfs *stbuf)
{
	ROUTE("statfs", path, 0, 0);
	(void)rp;
	/* `df /` must answer, and a synthetic node has no backing store of its
	 * own — every tier but `host` is materialised into the mirror, so that
	 * is the filesystem whose free space the caller is actually consuming. */
	int fd = r.tier == T_HOST ? host_fd : remote_fd;
	return fstatvfs(fd, stbuf) == -1 ? -errno : 0;
}

static int pt_flush(const char *path, struct fuse_file_info *fi)
{
	(void)path;
	int fd = dup((int)fi->fh);
	if (fd == -1) return -errno;
	return close(fd) == -1 ? -errno : 0;
}

/*
 * CRITERION 8'S SECOND HALF. A handle that was opened writable pushes DIRTY
 * before it closes, so cc copies the mirror's copy back to the source.
 *
 * READY MEANS CC HAS TAKEN OWNERSHIP OF THE PUSH, NOT THAT THE PUSH LANDED.
 * The awaiting half — a PostToolUse that blocks until it has, and poisons the
 * session if it has not — is 2026-0356's, deliberately (plan 2026-0355 §14).
 *
 * A file written through two handles pushes twice. The push is a full-content
 * copy, so that is idempotent; noted rather than defended against.
 */
static int pt_release(const char *path, struct fuse_file_info *fi)
{
	int fd = (int)fi->fh;

	if (fd >= 0 && fd < FDTIER_SLOTS && fd_dirty[fd] &&
	    (enum tier)fd_tier[fd] == T_PROJECT) {
		cache_invalidate(path);
		if (ccu_call(CCU_DIRTY, 0, path) != 0)
			policy_refuse("release", path, "dirty-push-refused");
	}
	if (fd >= 0 && fd < FDTIER_SLOTS) {
		fd_tier[fd] = 0;
		fd_dirty[fd] = 0;
	}
	close(fd);
	return 0;
}

static int pt_fsync(const char *path, int datasync, struct fuse_file_info *fi)
{
	(void)path;
	int rc = datasync ? fdatasync((int)fi->fh) : fsync((int)fi->fh);
	return rc == -1 ? -errno : 0;
}

static int pt_fallocate(const char *path, int mode, off_t off, off_t len,
			struct fuse_file_info *fi)
{
	(void)path;
	return fallocate((int)fi->fh, mode, off, len) == -1 ? -errno : 0;
}

static off_t pt_lseek(const char *path, off_t off, int whence,
		      struct fuse_file_info *fi)
{
	(void)path;
	off_t rc = lseek((int)fi->fh, off, whence);
	return rc == -1 ? -errno : rc;
}

/* xattr: reported through the routed tier, so a caller that consults them sees
 * the real answer of the tier that owns the file rather than a synthetic
 * ENOTSUP -- and never the other tier's. A synthetic node has no xattrs of its
 * own and must not borrow the host directory's. */
static void abspath(const struct route *r, const char *path, char *out, size_t n)
{
	const char *root = (r->fd == remote_fd) ? remote_root : host_root;
	snprintf(out, n, "%s%s", strcmp(root, "/") == 0 ? "" : root, path);
}

static int pt_setxattr(const char *path, const char *name, const char *value,
		       size_t size, int flags)
{
	ROUTE("setxattr", path, 0, CCU_STAT);
	(void)rp;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	return lsetxattr(abs, name, value, size, flags) == -1 ? -errno : 0;
}

static int pt_getxattr(const char *path, const char *name, char *value, size_t size)
{
	ROUTE("getxattr", path, 0, CCU_STAT);
	(void)rp;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	ssize_t n = lgetxattr(abs, name, value, size);
	return n == -1 ? -errno : (int)n;
}

static int pt_listxattr(const char *path, char *list, size_t size)
{
	ROUTE("listxattr", path, 0, CCU_STAT);
	(void)rp;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	ssize_t n = llistxattr(abs, list, size);
	return n == -1 ? -errno : (int)n;
}

static int pt_removexattr(const char *path, const char *name)
{
	ROUTE("removexattr", path, 0, CCU_STAT);
	(void)rp;
	if (SYNTHETIC(r.tier)) return -EOPNOTSUPP;
	char abs[PATH_MAX];
	abspath(&r, path, abs, sizeof(abs));
	return lremovexattr(abs, name) == -1 ? -errno : 0;
}

static const struct fuse_operations pt_ops = {
	.init        = pt_init,
	.getattr     = pt_getattr,
	.access      = pt_access,
	.readlink    = pt_readlink,
	.opendir     = pt_opendir,
	.readdir     = pt_readdir,
	.releasedir  = pt_releasedir,
	.mkdir       = pt_mkdir,
	.mknod       = pt_mknod,
	.unlink      = pt_unlink,
	.rmdir       = pt_rmdir,
	.symlink     = pt_symlink,
	.rename      = pt_rename,
	.link        = pt_link,
	.chmod       = pt_chmod,
	.chown       = pt_chown,
	.truncate    = pt_truncate,
	.utimens     = pt_utimens,
	.create      = pt_create,
	.open        = pt_open,
	.read        = pt_read,
	.write       = pt_write,
	.statfs      = pt_statfs,
	.flush       = pt_flush,
	.release     = pt_release,
	.fsync       = pt_fsync,
	.fallocate   = pt_fallocate,
	.lseek       = pt_lseek,
	.setxattr    = pt_setxattr,
	.getxattr    = pt_getxattr,
	.listxattr   = pt_listxattr,
	.removexattr = pt_removexattr,
};

static void pins_load(const char *file)
{
	FILE *f = fopen(file, "r");
	char  line[PATH_MAX + 64];

	if (!f) {
		fprintf(stderr, "cc-union: pins %s: %s\n", file, strerror(errno));
		exit(1);
	}
	while (fgets(line, sizeof(line), f))
		if (pins_parse_line(line) != 0) {
			fprintf(stderr, "cc-union: pins: %s\n", policy_err);
			exit(1);
		}
	fclose(f);
}

int main(int argc, char *argv[])
{
	const char *hr = getenv("CC_UNION_HOST_ROOT") ?: "/";
	const char *rr = getenv("CC_UNION_REMOTE");
	const char *pf = getenv("CC_UNION_PINS");
	const char *mp = getenv("CC_UNION_MNT");
	const char *tp = getenv("CC_UNION_TRACE");
	const char *fp = getenv("CC_UNION_REFUSALS");
	int probe;

	self_tgid     = getpid();
	mark_path     = getenv("CC_UNION_MARK_PATH");
	control_path  = getenv("CC_UNION_CONTROL");

	if (!rr || !pf) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_REMOTE and "
				"CC_UNION_PINS are both required\n");
		return 1;
	}
	/*
	 * THE MARK IS THE PROJECT TIER'S ONLY KEY. Without the marking event
	 * every caller is unmarked and the remote tier is unreachable, so the
	 * mount would serve a silent host-only filesystem that looks exactly
	 * like a containment success. Refuse instead.
	 */
	if (!mark_path) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_MARK_PATH is required; "
				"without it no caller is ever marked and the project tier "
				"is unreachable\n");
		return 1;
	}
	/* Same reasoning for the channel: a daemon that cannot reach cc can
	 * materialise nothing, so every project path would answer -EIO. */
	if (!control_path) {
		fprintf(stderr, "cc-union: REFUSED — CC_UNION_CONTROL is required; "
				"without cc's control socket no remote path can be "
				"materialised\n");
		return 1;
	}
	if (pthread_key_create(&control_key, control_close) != 0) {
		fprintf(stderr, "cc-union: REFUSED — could not create the control-socket key\n");
		return 1;
	}
	/* Connect once BEFORE mounting. An unconnectable socket discovered on
	 * the first getattr is a mount that came up and answers nothing. */
	if ((probe = control_connect()) < 0) {
		fprintf(stderr, "cc-union: REFUSED — cannot connect to cc's control "
				"socket at %s: %s\n", control_path, strerror(errno));
		return 1;
	}
	close(probe);
	ccu_xport.roundtrip = control_roundtrip;

	snprintf(host_root,   sizeof(host_root),   "%s", hr);
	snprintf(remote_root, sizeof(remote_root), "%s", rr);

	pins_load(pf);
	/* The mountpoint lies inside BOTH roots, so an unguarded union recurses
	 * forever the first time anything walks the tree. S1 §7.5. */
	if (mp && pin_add(T_HIDE, mp) != 0) {
		fprintf(stderr, "cc-union: REFUSED — %s\n", policy_err);
		return 1;
	}
	/* AFTER every pin is in: the ancestor set is derived from the final
	 * table, so the mountpoint's own parents are synthetic too. */
	anc_build();

	if ((host_fd = open(host_root, O_PATH | O_DIRECTORY)) == -1) {
		fprintf(stderr, "cc-union: host root %s: %s\n",
			host_root, strerror(errno));
		return 1;
	}
	if ((remote_fd = open(remote_root, O_PATH | O_DIRECTORY)) == -1) {
		fprintf(stderr, "cc-union: mirror %s: %s\n",
			remote_root, strerror(errno));
		return 1;
	}
	if (tp) {
		if (!(trace_fp = fopen(tp, "a"))) {
			fprintf(stderr, "cc-union: trace %s: %s\n", tp, strerror(errno));
			return 1;
		}
		setvbuf(trace_fp, NULL, _IOLBF, 0);
	}
	if (fp) {
		if (!(refusal_fp = fopen(fp, "a"))) {
			fprintf(stderr, "cc-union: refusal log %s: %s\n", fp, strerror(errno));
			return 1;
		}
		setvbuf(refusal_fp, NULL, _IOLBF, 0);
	}

	fprintf(stderr, "cc-union: host=%s mirror=%s pins=%zu synth=%zu "
		"markpath=%s control=%s tgid=%d\n",
		host_root, remote_root, npins, nancs, mark_path, control_path,
		(int)self_tgid);

	umask(0);
	return fuse_main(argc, argv, &pt_ops, NULL);
}
