// Ownership of a project's in-tree `CONVENTIONS.md` — the file a split-model
// project imports via `@CONVENTIONS.md`. Unlike the frozen inline snapshot the
// old flow baked into `CLAUDE.md` at creation, this file is *regenerated* so a
// project picks up improved convention text over time (mirroring how the
// projects-root `CLAUDE.md` is regenerated by src/rootClaudeMd.ts).
//
// Source of truth travels WITH the project: line 1 is a machine-readable marker
//   <!-- cc:conventions design-guidelines,testing-guidelines -->
// listing the selected slugs, and the body below is the composed convention
// text. The whole file is committed with the project, so any cc instance (a
// fresh install, a moved/renamed project, an import into a different store) can
// regenerate from the file alone.
//
// No sentinel/backup machinery (cf. rootClaudeMd.ts): CONVENTIONS.md is born
// app-owned — created fresh only for split-model projects — so there is no
// pre-existing hand-edited file to protect. The safety net is the rule in
// ensureProjectConventionsMd: regeneration composes whichever marker slugs it
// *can* resolve and names the rest in a visible in-body note, keeping them in
// the marker so they recover verbatim if they resolve again; it declines to
// write only when no slug resolves to a body, leaving the committed file
// untouched (never blanks it). Projects with no marker (grandfathered, or no
// conventions selected) are skipped entirely.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { listProjects } from './projects.ts';
import { composeProjectConventionsBlock, getCatalog } from './projectConventions.ts';

const CONVENTIONS_FILENAME = 'CONVENTIONS.md';

// Line-1 marker: `<!-- cc:conventions a,b,c -->` (slugs are comma-safe — the
// slug charset is [a-zA-Z0-9._-] plus plugin `<id>/<slug>`, never a comma).
const MARKER_RE = /^<!-- cc:conventions ?(.*?) ?-->$/;

interface RegenerateLog {
  log?: (...args: unknown[]) => void;
  warn?: (...args: unknown[]) => void;
}

export function conventionsTargetPath(projectPath: string): string {
  return path.join(projectPath, CONVENTIONS_FILENAME);
}

export function buildMarker(slugs: string[]): string {
  return slugs.length ? `<!-- cc:conventions ${slugs.join(',')} -->` : '<!-- cc:conventions -->';
}

// Visible in-body note naming marker slugs that don't resolve locally. This is
// system-prompt text for every worker in the project, so it states a fact about
// the document and nothing else — no imperative, no second person. Slugs keep
// marker order. Real convention bodies all start with `## `, so the blockquote
// can never be mistaken for one.
function unresolvedNote(missing: string[]): string {
  return `> Omitted — not available in this cc instance: ${missing.map(s => `\`${s}\``).join(', ')}. `
    + `Text returns automatically once available again.`;
}

// Parse the first line of a CONVENTIONS.md. Returns the slug array (possibly
// empty) if it is a valid marker, else null (not our file / grandfathered).
export function parseMarker(firstLine: string | null | undefined): string[] | null {
  const m = MARKER_RE.exec(firstLine ?? '');
  if (!m) return null;
  const inner = m[1].trim();
  return inner === '' ? [] : inner.split(',').map(s => s.trim()).filter(Boolean);
}

// Full CONVENTIONS.md document for a selection: marker + composed bodies.
// `missing` (marker slugs that don't resolve here) is kept in the MARKER — so the
// convention recovers verbatim if it returns — but contributes a visible note
// instead of a body. Unknown slug outside `missing` → 400 (via
// composeProjectConventionsBlock); callers at project creation rely on that.
export async function composeProjectConventionsDoc(slugs: string[], missing: string[] = []): Promise<string> {
  const marker = buildMarker(slugs);
  const gone = new Set(missing);
  const body = await composeProjectConventionsBlock(slugs.filter(s => !gone.has(s)));
  if (gone.size === 0) return `${marker}\n${body || '\n'}`;
  return `${marker}\n\n${unresolvedNote(missing)}\n${body}`;
}

// Regenerate one project's CONVENTIONS.md from its own in-tree marker.
//   - file missing              → { skipped: 'no-file' }
//   - line 1 not a marker       → { skipped: 'no-marker' }
//   - zero-slug marker          → { skipped: 'empty-marker' }
//   - nothing resolves to a body → { skipped: 'unresolvable' }  (never blanks)
//   - some slugs unresolvable   → recompose the rest + a note → { regenerated: true, missing }
//   - all slugs resolve         → recompose + overwrite → { regenerated: true, missing: [] }
export async function ensureProjectConventionsMd(projectName: string, { log }: { log?: RegenerateLog } = {}): Promise<
  | { skipped: 'no-project' }
  | { skipped: 'no-file' }
  | { skipped: 'no-marker' }
  | { skipped: 'empty-marker' }
  | { skipped: 'unresolvable'; missing: string[] }
  | { path: string; regenerated: true; missing: string[] }
> {
  const projects = await listProjects();
  const proj = projects.find(p => p.name === projectName);
  if (!proj) return { skipped: 'no-project' };
  const target = conventionsTargetPath(proj.path);

  let existing: string;
  try { existing = await fs.readFile(target, 'utf8'); }
  catch (e) { if (errCode(e) === 'ENOENT') return { skipped: 'no-file' }; throw e; }

  const slugs = parseMarker(existing.split('\n', 1)[0]);
  if (slugs === null) return { skipped: 'no-marker' };
  // A zero-slug marker is vacuously resolvable, so recomposing would blank any
  // hand-authored body. cc never emits one (create gates on ≥1 slug), so treat
  // it like the other skip branches — leave the committed file untouched.
  if (slugs.length === 0) return { skipped: 'empty-marker' };

  // Resolve against the local catalog. Unresolvable slugs (a custom convention
  // absent on this instance, a disabled/absent plugin, a retired seed) stay in
  // the marker — so the text returns verbatim if they do — but drop out of the
  // body in favour of a visible note. The resolvable ones refresh normally.
  const bySlug = new Map((await getCatalog()).map(e => [e.slug, e]));
  const missing = slugs.filter(s => !bySlug.has(s));
  // Never trade committed text for a bare note: if nothing that resolves
  // contributes a body (every slug missing, or the survivors are scaffold-only
  // plugin conventions), leave the committed file exactly as-is.
  if (missing.length > 0 && !slugs.some(s => bySlug.get(s)?.body)) {
    if (log?.log) log.log(`CONVENTIONS.md left as-is for '${projectName}': unresolvable ${missing.join(', ')}`);
    return { skipped: 'unresolvable', missing };
  }

  const content = await composeProjectConventionsDoc(slugs, missing);
  await fs.writeFile(target, content);
  if (log?.log) {
    log.log(missing.length
      ? `CONVENTIONS.md regenerated without unresolvable ${missing.join(', ')}: ${target}`
      : `CONVENTIONS.md regenerated: ${target}`);
  }
  return { path: target, regenerated: true, missing };
}

// Boot / post-mutation fan-out over every project. Per-project try/catch so one
// bad project can't abort the sweep. `.conduct` is excluded by listProjects().
export async function regenerateAllProjectConventions({ log }: { log?: RegenerateLog } = {}): Promise<Array<{ name: string; [key: string]: unknown }>> {
  const projects = await listProjects();
  const results: Array<{ name: string; [key: string]: unknown }> = [];
  for (const p of projects) {
    try { results.push({ name: p.name, ...(await ensureProjectConventionsMd(p.name, { log })) }); }
    catch (e) {
      if (log?.warn) log.warn(`CONVENTIONS.md regenerate failed for '${p.name}': ${errMsg(e)}`);
      results.push({ name: p.name, error: errMsg(e) });
    }
  }
  return results;
}

// The `code` on a thrown Node error (e.g. 'ENOENT'), or undefined — the
// narrowing point for error-code checks (catch variables are `unknown` under
// strict). Duplicated from storeLock.ts: it's four lines, and importing it
// across modules would couple every store to storeLock for one helper.
function errCode(e: unknown): string | undefined {
  if (typeof e !== 'object' || e === null) return undefined;
  const code = (e as { code?: unknown }).code;
  return typeof code === 'string' ? code : undefined;
}

function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}
