// Ownership of a project's in-tree `CONVENTIONS.md` — the file a split-model
// project imports via `@CONVENTIONS.md`. Unlike the frozen inline snapshot the
// old flow baked into `CLAUDE.md` at creation, this file is *regenerated* so a
// project picks up improved convention text over time (mirroring how the
// projects-root `CLAUDE.md` is regenerated by src/rootClaudeMd.js).
//
// Source of truth travels WITH the project: line 1 is a machine-readable marker
//   <!-- cc:conventions design-guidelines,testing-guidelines -->
// listing the selected slugs, and the body below is the composed convention
// text. The whole file is committed with the project, so any cc instance (a
// fresh install, a moved/renamed project, an import into a different store) can
// regenerate from the file alone.
//
// No sentinel/backup machinery (cf. rootClaudeMd.js): CONVENTIONS.md is born
// app-owned — created fresh only for split-model projects — so there is no
// pre-existing hand-edited file to protect. The safety net is the no-op-safe
// rule in ensureProjectConventionsMd: regeneration only ever overwrites when it
// can fully resolve the marker's slugs; otherwise it leaves the committed file
// untouched (never blanks it). Projects with no marker (grandfathered, or no
// conventions selected) are skipped entirely.

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { listProjects } from './projects.ts';
import { composeProjectConventionsBlock, getCatalog } from './projectConventions.ts';

const CONVENTIONS_FILENAME = 'CONVENTIONS.md';

// Line-1 marker: `<!-- cc:conventions a,b,c -->` (slugs are comma-safe — the
// slug charset is [a-zA-Z0-9._-] plus plugin `<id>/<slug>`, never a comma).
const MARKER_RE = /^<!-- cc:conventions ?(.*?) ?-->$/;

export function conventionsTargetPath(projectPath) {
  return path.join(projectPath, CONVENTIONS_FILENAME);
}

export function buildMarker(slugs) {
  return slugs.length ? `<!-- cc:conventions ${slugs.join(',')} -->` : '<!-- cc:conventions -->';
}

// Parse the first line of a CONVENTIONS.md. Returns the slug array (possibly
// empty) if it is a valid marker, else null (not our file / grandfathered).
export function parseMarker(firstLine) {
  const m = MARKER_RE.exec(firstLine ?? '');
  if (!m) return null;
  const inner = m[1].trim();
  return inner === '' ? [] : inner.split(',').map(s => s.trim()).filter(Boolean);
}

// Full CONVENTIONS.md document for a selection: marker + composed bodies.
// Unknown slug → 400 (via composeProjectConventionsBlock) — callers at project
// creation rely on this to reject a bad slug list.
export async function composeProjectConventionsDoc(slugs) {
  const marker = buildMarker(slugs);
  const body = await composeProjectConventionsBlock(slugs);
  return `${marker}\n${body || '\n'}`;
}

// Regenerate one project's CONVENTIONS.md from its own in-tree marker.
//   - file missing            → { skipped: 'no-file' }
//   - line 1 not a marker     → { skipped: 'no-marker' }
//   - any slug unresolvable   → { skipped: 'unresolvable' }  (never blanks)
//   - all slugs resolve       → recompose + overwrite → { regenerated: true }
export async function ensureProjectConventionsMd(projectName, { log } = {}) {
  const projects = await listProjects();
  const proj = projects.find(p => p.name === projectName);
  if (!proj) return { skipped: 'no-project' };
  const target = conventionsTargetPath(proj.path);

  let existing;
  try { existing = await fs.readFile(target, 'utf8'); }
  catch (e) { if (e.code === 'ENOENT') return { skipped: 'no-file' }; throw e; }

  const slugs = parseMarker(existing.split('\n', 1)[0]);
  if (slugs === null) return { skipped: 'no-marker' };
  // A zero-slug marker is vacuously resolvable, so recomposing would blank any
  // hand-authored body. cc never emits one (create gates on ≥1 slug), so treat
  // it like the other skip branches — leave the committed file untouched.
  if (slugs.length === 0) return { skipped: 'empty-marker' };

  // Resolve against the local catalog. If any slug is missing (a custom
  // convention absent on this instance, a disabled/absent plugin, a retired
  // seed), leave the committed file exactly as-is.
  const known = new Set((await getCatalog()).map(e => e.slug));
  const missing = slugs.filter(s => !known.has(s));
  if (missing.length > 0) {
    if (log?.log) log.log(`CONVENTIONS.md left as-is for '${projectName}': unresolvable ${missing.join(', ')}`);
    return { skipped: 'unresolvable', missing };
  }

  const content = await composeProjectConventionsDoc(slugs);
  await fs.writeFile(target, content);
  if (log?.log) log.log(`CONVENTIONS.md regenerated: ${target}`);
  return { path: target, regenerated: true };
}

// Boot / post-mutation fan-out over every project. Per-project try/catch so one
// bad project can't abort the sweep. `.conduct` is excluded by listProjects().
export async function regenerateAllProjectConventions({ log } = {}) {
  const projects = await listProjects();
  const results = [];
  for (const p of projects) {
    try { results.push({ name: p.name, ...(await ensureProjectConventionsMd(p.name, { log })) }); }
    catch (e) {
      if (log?.warn) log.warn(`CONVENTIONS.md regenerate failed for '${p.name}': ${e.message}`);
      results.push({ name: p.name, error: e.message });
    }
  }
  return results;
}
